### ISSUE TITLE
https://www.facebook.com/mohamedselim9811

### ISSUE THREAD

**Issue by selim2020** [facebookresearch/nevergrad#1037]
## Steps to reproduce

  1. _____
  2. _____
  3. _____

## Observed Results

  * What happened?  This could be a description, log output, etc.

## Expected Results

  * What did you expect to happen?

## Relevant Code

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by selim2020** [comment]
المتابعة التلقائية أثناء أستقبال طلب الصداقة لا يعمل

**Comment by jrapin** [comment]
Closing for lack of relevance and content
