### ISSUE TITLE
ParaPortfolio Throwing error with using tell not ask on DE.

### ISSUE THREAD

**Issue by smestern** [facebookresearch/nevergrad#1052]
## Steps to reproduce

  1. Initialize ParaPortfolio in high dimension (param_n=11), with large workers (n_workers=500), and budget (500*100)
  2. Run >2 rounds in ask and tell format
  3. DE will fail to delete a member of its population

## Observed Results

It appears DE try to delete a member of the population but fails to find it. The full error log is here:

<details>

> Traceback (most recent call last):
>    File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
>       "__main__", mod_spec)
>     File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
>       exec(code, run_globals)
>     File "c:\Users\smestern\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
>       cli.main()
>     File "c:\Users\smestern\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
>       run()
>     File "c:\Users\smestern\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file       
>       runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
>     File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 263, in run_path
>       pkg_name=pkg_name, script_name=fname)
>     File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 96, in _run_module_code
>       mod_name, mod_spec, pkg_name, script_name)
>     File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
>       exec(code, run_globals)
>     File "c:\Users\smestern\Documents\dropbox\Dropbox\neuronex_cortical\code\batch_SNM_Fitter.py", line 92, in <module>
>       main()
>     File "c:\Users\smestern\Documents\dropbox\Dropbox\neuronex_cortical\code\batch_SNM_Fitter.py", line 81, in main
>       res = fit_cell(fp)
>     File "c:\Users\smestern\Documents\dropbox\Dropbox\neuronex_cortical\code\batch_SNM_Fitter.py", line 52, in fit_cell
>       temp_df = snm_fit.run_optimizer(fp, cm, taum, rounds_=175, batch_size_=500, optimizer='ng', sweep_upper_cut=sweep_upper)
>     File "c:\Users\smestern\Documents\dropbox\Dropbox\neuronex_cortical\code\snm_fit_adif.py", line 174, in run_optimizer
>       results = nevergrad_opt(model, vars_stack, _labels, id=cell_id) #if the optimizer is ng pass in to ng
>     File "c:\Users\smestern\Documents\dropbox\Dropbox\neuronex_cortical\code\snm_fit_adif.py", line 325, in nevergrad_opt
>       opt.tell(param_list, y) ##Tells the optimizer the param - error pairs so it can learn
>     File "c:\Users\smestern\Documents\dropbox\Dropbox\neuronex_cortical\code\b2_model\optimizer.py", line 74, in tell
>       self.opt.tell(row, errors[i])
>     File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\nevergrad\optimization\base.py", line 369, in tell
>       self._internal_tell_candidate(candidate, loss)
>     File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\nevergrad\optimization\optimizerlib.py", line 1233, in _internal_tell_candidate
>       opt.tell(candidate, loss)
>     File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\nevergrad\optimization\base.py", line 372, in tell
>       self._internal_tell_not_asked(candidate, loss)
>     File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\nevergrad\optimization\differentialevolution.py", line 200, in _internal_tell_not_asked
>       del self.population[discardable]

</details>

## Expected Results

  tell not ask succeeds with DE and the optimizer continues. 

This appears to be related to commit #682. Error appears with ng 0.4.3 but not 0.4.2
I sadly cannot share the full script. However I can throw together an example script if need be.

**Comment by jrapin** [comment]
Hi!
Thanks for the detailed steps, I was able to reproduce it, and figure out there was an important interaction problem between PSO and DE in ParaPortfolio, it's hopefully fixes in master now ;)
