### ISSUE TITLE
RuntimeWarning: overflow encountered in power

### ISSUE THREAD

**Issue by gcp** [facebookresearch/nevergrad#1064]
```
nevergrad/parametrization/data.py:405: RuntimeWarning: overflow encountered in power
  self._value = data_reduc if reference.exponent is None else reference.exponent ** data_reduc
```

STR:
1) Run attached script, which uses Nevergrad BO on a mocked optimization problem: https://gist.github.com/gcp/1d695aa4732c1df252374c0b26dd5f32

This doesn't occur with other optimizers.

**Comment by jrapin** [comment]
Hi,
Thanks for raising the issue, I probably won't have time to investigate closely before next week, sorry (investigating is also made difficult since this part of the code has been completely refactored in master :s). I'll come back to you asap.

**Comment by jrapin** [comment]
I'll close this since this does not happen anymore on master, given the huge changes that have happen. I'll still update BO soon because the initial sampling was not taking bounds properly into account #1070.
Let me know if you still encounter the issue after updating!
