### ISSUE TITLE
Custom portfolio which accepts list of optimizers

### ISSUE THREAD

**Issue by smestern** [facebookresearch/nevergrad#1084]
## Feature Request

This is less of an issue and more of a feature request. While running my code, I was thinking it would be nice to have a portfolio that could be easily customized by simply passing in a list of registered optimizers (similar to using the chaining method).
I find this is useful on my end to combine several sampling/random searches and a TBPSA etc.

## Relevant Code
A rudimentary implementation that seems to work on my end:

  ```python
 class CustomPortfolio(ng.optimizers.Portfolio):
    """"""

    def __init__(self, parametrization, budget = None, num_workers = 1, optimizers = None) -> None:
        super().__init__(parametrization, budget=budget, num_workers=num_workers)
        assert budget is not None

        if optimizers  is None:
            optimizers = [
            ng.optimizers.CMA, 
            ng.optimizers.TwoPointsDE, 
            ng.optimizers.PSO,
            ng.optimizers.TBPSA,  
            ng.optimizers.ScrHammersleySearch,  
        ]

        def intshare(n: int, m: int):
            x = [n // m] * m
            i = 0
            while sum(x) < n:
                x[i] += 1
                i += 1
            return tuple(x)

        nws = intshare(num_workers, len(optimizers))
        self.which_optim = []
        for i, nw in enumerate(nws): #Using List comprehension did not work for whatever reason
            self.which_optim += [i] * nw

        assert len(self.which_optim) == num_workers
        self.optims: tp.List[base.Optimizer] = [opt(self.parametrization, num_workers=nw, budget=(budget // len(self.which_optim)) * nw) for opt, nw in zip(optimizers, nws)]
  ```

Then the user could use it as such.

```python
opt = CustomPortfolio(params, budget=200, num_workers=20, 
                                    optimizers = [ng.optimizers.CMA, ng.optimizers.CMA, ng.optimizers.ScrHammersleySearch])
```

granted this implementation will not work with optimizers that do not accept >1 num_workers (e.g. SQP). This trusts the user knows enough to not do this. Although, there might be a way to determine if a user pushes one through and handle it on the backend.

**Comment by jrapin** [comment]
Hi @smestern 
Indeed, it's a good point, there are many Portfolio based optims that should be merge into one "ConfiguredOptimizer" which should solve a few problems in the process: allow budget=None, deal specifically with non-parallelizable optimizers (SQP as you mentioned) etc.
I can give it a go (with a few weeks I guess) but I'm happy to try and merge your contribution if you want to give it a try. I would not expect it to solve everything at once though, which would be hard, I'll build on it afterwards if need be.

**Comment by jrapin** [comment]
@smestern, it took some time sorry but it's now merged
