### ISSUE TITLE
Question: Is a new post release planned for 0.4.3?

### ISSUE THREAD

**Issue by pbosch** [facebookresearch/nevergrad#1092]
Hi all

I'm aware that this is not a popular question, but I am wondering if a new post release is planned soon? I mainly ask this because pull request #1073 added functionality that exposes phi and omega through ConfiguredPSO which can easily be used in Ray Tune. While pulling Nevergrad directly from Github is fine for me, it's a bit of an issue when integrating it and offering the app to users who are not necessarily that tech savy. 

Kind regards
Patrick

**Comment by jrapin** [comment]
Released ;)
Don't hesitate to ask, I'm ready to release "post" release anytime, I'll be more careful with "standard" releases though.

**Comment by pbosch** [comment]
I'm happy to hear that! I fully understand that a standard release should be planned more carefully.
I will be using this post release immediately, thanks!
