### ISSUE TITLE
How can I prevent the library from printing unnecessary logs?

### ISSUE THREAD

**Issue by philipperemy** [facebookresearch/nevergrad#1101]
How can I prevent the library from printing unnecessary logs?
```
10.61%. (3_w,6)-aCMA-ES (mu_w=2.0,w_1=63%) in dimension 2 (seed=nan, Sun Apr 18 12:42:58 2021)
29.30%. (3_w,6)-aCMA-ES (mu_w=2.0,w_1=63%) in dimension 2 (seed=nan, Sun Apr 18 12:43:00 2021)
36.37%. (3_w,6)-aCMA-ES (mu_w=2.0,w_1=63%) in dimension 2 (seed=nan, Sun Apr 18 12:43:02 2021)
```

**Comment by jrapin** [comment]
This was a problem with the wrapper around CMA which was not aggressive enough in suppressing the prints. I've updated it and pushed a new "post" version, you should not have prints anymore now. Sorry for the bother and don't hesitate to open new issues if need be ;)

**Comment by philipperemy** [comment]
Thank you @jrapin !!
