### ISSUE TITLE
Sigma

### ISSUE THREAD

**Issue by wenyanyy** [facebookresearch/nevergrad#1125]
Hi,

I'm using nevergrad platform in facebook Robyn code, where using parametrizing and Optimizers . I would like to customize the step when doing Parametrizing. I noticed you write code "param["array"].set_mutation(sigma=10)". Could you please tell me what's meaning for sigma=10?sigma is standard deviation? 

Also I'm not sure I totally understanding the parametrizing and Optimizers after seeing the platform. I think parametrizing is to randomly choose number given bound for the parameter and using the number to perform optimizer. I'm not sure i'm think right? Could you please explain them?

Thanks 
Regina

**Comment by jrapin** [comment]
> Could you please tell me what's meaning for sigma=10?sigma is standard deviation?

Yes, this is a standard deviation. You actually see it as a step size, like the learning rate. The difference is that most algorithm use a gaussian noise as a step size.

> I think parametrizing is to randomly choose number given bound for the parameter and using the number to perform optimizer. I'm not sure i'm think right? Could you please explain them?

Parametrization is here to express all you know about the problems. Eg: the bounds, the scale (through sigma), for discrete variables whether they are ordered or categorical, sometimes other special structures as well.
These information will be used by some optimizers (eg: `NGOpt`) to select the best approach to use, and the parametrization provides helpful methods for the optimizers: sampling a new random point as you mention, but also mapping to an unconstrained space where optimization is easier.

Does that help?

**Comment by wenyanyy** [comment]
Thanks Jrapin. sigma is the standard deviation of the bound?
Also, I would like to get same results every experiments so I want to set seed. Could you tell me how to set seed within nevergrad in R code? 

Thanks a lot

**Comment by wenyanyy** [comment]
if (length(hyper_bound_local_ng) !=0) {
    my_tuple <- tuple(num_hyppar_ng)
   # list <- c(1,2,3,4,5,6,7,8,9)
    #instrumentation<-ng$p$TransitionChoice(list)
    #instrumentation$repetitions <-30
    instrumentation <- ng$p$Array(shape=my_tuple)
    instrumentation$set_bounds(0., 1.)
    instrumentation$set_mutation(sigma=3)
    np$random$RandomState <- 12
    optimizer <- ng$optimizers$registry[optimizer_name](instrumentation, budget=iterTotal, num_workers=set_cores)
    if (activate_calibration==F) {
      optimizer$tell(ng$p$MultiobjectiveReference(), tuple(1.0, 1.0))
    } else {
      optimizer$tell(ng$p$MultiobjectiveReference(), tuple(1.0, 1.0, 1.0))
    }
    # Creating a hyperparameter vector to be used in the next learning.
  } 

Above is my code and it gives me a error that :  TypeError: 'float' object is not callable. Detailed traceback:
  File "C:\Users\reghuang\ANACON~1\lib\site-packages\nevergrad\optimization\base.py", line 345, in tell
    self._hypervolume_pareto = mobj.HypervolumePareto(upper_bounds=loss, seed=self._rng)
  File "C:\Users\reghuang\ANACON~1\lib\site-packages\nevergrad\optimization\base.py", line 142, in _rng
    return self.parametrization.random_state
  File "C:\Users\reghuang\ANACON~1\lib\site-packages\nevergrad\parametrization\core.py", line 309, in random_state
    self._set_random_state(np.random.RandomState(seed)).


Could you please let me know the reason and how to write the correct code? I'm very struggle with it.  Thanks

**Comment by jrapin** [comment]
> sigma is the standard deviation of the bound?

not the bounds no, it's really the step size for looking for a new candidate

> Could you tell me how to set seed within nevergrad in R code?

I don't know about R code, but I would expect that the following would work:
`instrumentation$random_state$seed(your_seed)`
Remove `np$random$RandomState <- 12` which is incorrect (see numpy doc) and may trigger the unexpected behavior that you saw

**Comment by wenyanyy** [comment]
Hi Jeremy,


Thank you for replying me. I tried the code
Instrumentation$set_bounds(0.,1.)
instrumentation$random_state$seed(12)
and it doesn’t give me error. However I still get random and different results after trying twice. Do you think it’s possible to fix the results?

Best,

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jrapin** [comment]
There are tests verifying that all the optimizers are deterministic, so this should not happen. It may be due to the R interface (absolutely no idea how it works) or something which is not deterministic in your code :s
