### ISSUE TITLE
Adding branching info inside the CSV files ?

### ISSUE THREAD

**Issue by teytaud** [facebookresearch/nevergrad#1136]
Carola + colleagues want to have the NGOpt branching decisions inside the CSV files.
Jeremy, can you recommend a solution for that ?

**Comment by teytaud** [comment]
@CarolaDoerr  @jrapin

**Comment by jrapin** [comment]
Hi @CarolaDoerr 
What is the exact aim? Being able to screen the results manually through the csv?

**Comment by CarolaDoerr** [comment]
Hi Jeremy, I would like to see how the individual base algorithms perform. And ideally, I would just like to be able to use the csv files from the dashboard to do this, without requiring some sort of annotation.

**Comment by jrapin** [comment]
This is now working in the master branch

**Comment by CarolaDoerr** [comment]
cool. Thank you! Will you make the annotated csv files available on the dashboard? Would be really useful!

**Comment by jrapin** [comment]
> cool. Thank you! Will you make the annotated csv files available on the dashboard? Would be really useful!

That should happen automatically when @teytaud update his version of the code
