### ISSUE TITLE
python3.6 logging is broken with Never grad 0.4.2.post6

### ISSUE THREAD

**Issue by rojan507** [facebookresearch/nevergrad#1248]
## Steps to reproduce

logging.basicConfig(filename='logs/log.log', level=logging.DEBUG)
logging.debug('---Log file----')

## Observed Results

  * What happened?  This could be a description, log output, etc.

No logging produced 

## Expected Results

Logging should appear in lo.log file  if you downgrade to very old version it works

  * What did you expect to happen?

## Relevant Code

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by jrapin** [comment]
Hi @rojan507 
here's hardly any logging in nevergrad for now (we should add some indeed)
What do you expect to see, and what did you use to see?
I see only these two PRs which could have changed the behavior #1193 #1209
