### ISSUE TITLE
Downloading Files from Dashboard not always possible

### ISSUE THREAD

**Issue by CarolaDoerr** [facebookresearch/nevergrad#1258]
When I try to download the zip files from the dashboard, I often get a message telling me the following (even if it is the first time after a while I try to download files). Anything that I can do to get access?

Error 1015 Ray ID: 697583dbda8fee44 • 2021-10-01 11:57:43 UTC
You are being rate limited
What happened?
The owner of this website (dl.fbaipublicfiles.com) has banned you temporarily from accessing this website.

**Comment by teytaud** [comment]
This happens frequently, I am trying to setup a new dashboard somewhere else.
I've sent CSV files directly to you.
Looking for a solution for hosting the dashboard. Maybe I can make it compact (like PDF export with medium resolution) e.g. on the facebook group nevergradusers and just send detailed files on demand.
