### ISSUE TITLE
the performance of NGOpt is far worse than DE and even RandomSearch which is not excepted

### ISSUE THREAD

**Issue by xinhongri** [facebookresearch/nevergrad#1259]
Dear,

I have read your paper 'Versatile Black-Box Optimization' and use your algorithm of NGOpt in the https://facebookresearch.github.io/nevergrad/index.html to perform a discrete optimization.

However, I find that the performance is far worse than DE and even RandomSearch which is not excepted.

Could you tell me in what condition this phenomenon will happen?

Are there important settings for NGOpt?

Thanks a lot!

**Comment by teytaud** [comment]
As discussed in chat, the fact that algorithm A is better than algorithm B can always happen, for a specific problem. A link to your github code (if available) would be great for trying to help you; in particular if you extract the key lines in which you create the optimization method and you run it would help us a lot for trying to help you.
