### ISSUE TITLE
GitHub tag vs PyPI release version and next release version

### ISSUE THREAD

**Issue by a-mazzetto** [facebookresearch/nevergrad#1497]
Hello,
I noticed that the GitHub version tagged v0.5.0 is not aligned with version v0.5.0 on PyPI, as a few subsequent commits fall under the same tag. One of which implements a penalization in the `tell()` method that fits my needs: may I ask when are you planning for a new release?
Thank you

**Comment by teytaud** [comment]
Sorry for the enormous delay, I typically read mostly the nevergradusers group and come to read github issues when they have been discussed there... presumably the issues you mention are solved.
I'll try to check github issues more frequently in the future, there were really helpful comments here.
