### ISSUE TITLE
examples of DE algorithm

### ISSUE THREAD

**Issue by beeevita** [facebookresearch/nevergrad#1504]
Are there any examples of differential evolution usage?

Thanks for replying.

**Comment by teytaud** [comment]
Hello! Just pick up any example and put DE as an algorithm. Then you can try also many of the DE variants.
For example,
import nevergrad as ng
import numpy as np
ng.optimizers.registry["DE"](5, 1000).minimize(lambda x: np.linalg.norm(x-np.array(range(5))))
Array{(5,)}:[-0.01746634  0.99310113  2.0081899   2.99205557  4.00086407]

and you can use "TwoPointsDE" or many other DE

['DE', 'TwoPointsDE', 'VoronoiDE', 'RotatedTwoPointsDE', 'LhsDE', 'QrDE', 'QODE', 'SPQODE', 'QOTPDE', 'LQOTPDE', 'LQODE', 'SODE', 'NoisyDE', 'AlmostRotationInvariantDE', 'RotationInvariantDE', 'DiscreteDE', 'RecMutDE', 'MutDE', 'NLOPT_LN_NELDERMEAD', 'TinyLhsDE', 'TinyQODE', 'ASCMADEthird', 'MetaModelDE', 'MetaModelQODE', 'NeuralMetaModelDE', 'SVMMetaModelDE', 'RFMetaModelDE', 'MetaModelTwoPointsDE', 'NeuralMetaModelTwoPointsDE', 'SVMMetaModelTwoPointsDE', 'RFMetaModelTwoPointsDE', 'GeneticDE', 'MemeticDE', 'QNDE', 'OpoDE', 'OpoTinyDE']
