### ISSUE TITLE
Documentation Bug: Examples - Nevergrad for Machine Learning

### ISSUE THREAD

**Issue by shirsho-12** [facebookresearch/nevergrad#1516]
https://facebookresearch.github.io/nevergrad/machinelearning.html
In the first example in the page, the `ng.P.Log` function has parameters `a_min=0.0001, a_max=1` which is not consistent with the current `ng.P.Log` function.

This should be `lower` and `upper` respectively.

**Comment by teytaud** [comment]
Fixed now.
