### ISSUE TITLE
Multiple constraints

### ISSUE THREAD

**Issue by Oguked** [facebookresearch/nevergrad#1594]
I couldn't find an option to add multiple constraints. I want to optimize in 3d space. Several separate 3d regions should be part of the search space. 

My use case is sensor placement optimization. I want to define disconnected regions where sensors can be placed, e.g. certain areas at different walls of a robot cell. The optimizer should provide solutions within these regions. How can I define a parameter space like that?

**Comment by teytaud** [comment]
Hello! There is no problem for multiple constraints.
You can add constraints with the contraint_violation mechanism.

For example with ask and tell:
optimizer.tell(candidate, value, [constraint_violation1, constraint_violation2, constraint_violation3])

Other examples at: https://facebookresearch.github.io/nevergrad/optimization.html

(register_cheap_constraint is another possibility, but for most users constraint_violations is better)

**Comment by xyyylll** [comment]
when I use optimizer.tell(candidate, value, [constraint_violation1, constraint_violation2, constraint_violation3]), the warning is:  optimizer.tell(candidate, objective_value, constraint_violations) TypeError: tell() takes 3 positional arguments but 4 were given
