### ISSUE TITLE
Latest version (1.02) does not follow semantic versioning conventions

### ISSUE THREAD

**Issue by emilyhunt** [facebookresearch/nevergrad#1598]
The [latest version](https://github.com/facebookresearch/nevergrad/releases/tag/1.02) of the package is tagged as version `1.02`, which does not follow [semantic versioning](https://semver.org/) conventions (and is probably a typo - was it supposed to be 1.0.2?)

Ideally the latest release's version number would be edited so that it could be specified against correctly in e.g. project dependencies.

**Comment by teytaud** [comment]
Excellent remark... showing the drawback of having a very poor vision, I have double checked the version number several times without noticing any error.
I'm impressed :-)
