### ISSUE TITLE
Set up step size in nevergrad

### ISSUE THREAD

**Issue by Siddharth8** [facebookresearch/nevergrad#1604]
I am using nevergrad to optimize and has got several hyperparameters to tune in. 
I am assigning one of them as x = ng.p.Scalar(lower=0, upper=1) and nevergrad takes any value between 0 to 1. However I want to include step size like increase by 0.1 always so values can be any from 0, 0.1, 0.2, 0.3 ... 1. I tried looking into how to achieve this in nevergrad but no success. Can anyone please help me to setup this step size ?

**Comment by teytaud** [comment]
Hello.
If I understand correctly, you want x to be in {0, 0.1, 0.2, ..., 1.} ?
A solution for this is to use 
ng.p.Scalar(lower=0., upper=10.).set_integer_casting() and divide by 10.
For example
x = [float(ng.p.Scalar(lower=0., upper=10.).set_integer_casting().sample().value) / 10. for _ in range(1000)] ; print(min(x), max(x), x[:15])

Have a great day.
