### ISSUE TITLE
CMA optimizer error: InjectionWarning: orphanated injected solution

### ISSUE THREAD

**Issue by andrewjgray1001** [facebookresearch/nevergrad#1609]
## Steps to reproduce

  1. create instance of ng.optimizers.CMA
  2. call minimize with a lot of workers

note:
this is using a pre-existing utility called Model_Evaluator which parallelizes requests across multiple processes/machines, it has been used extensively in optimizations and has never given any problems. In this example it is set to work with 40 processes. The threadPoolExecutor is just a device to forward multiple calls to the evaluator.

The error implies that if there is too high a degree of parallelization, the logic inside minimize fails, because the function requests (ask) somehow get out of sync with the results returned (tell). The same error occurs whether batch mode is True or False.

## Observed Results

the optimizer runs for a while, probably running several hundred evaluations, then produces regular errors like: 

evolution_strategy.py:2981: InjectionWarning: orphanated injected solution

then fails with error:

RuntimeError: Mean shift samples are expected but missing.
This happens if, for example, `ask` is called  more than once, without calling `tell`
(because the first call removes the samples from the injection list).
`cma.sigma_adaptation.CMAAdaptSigmaTPA` step-size adaptation generates mean shift
samples and relies on them.

## Expected Results

  The optimizer should work

## Relevant Code

     # Set up the optimizer
    optimizer = ng.optimizers.CMA(parametrization=num_weights, budget=1000000, num_workers=num_workers)

    model_eval = Model_Evaluator(config)

    with futures.ThreadPoolExecutor(max_workers=optimizer.num_workers) as executor:
        recommendation = optimizer.minimize(model_eval.f_eval, executor=executor, batch_mode=True)

****

**Comment by teytaud** [comment]
I tried again with the following code:
=========
import nevergrad as ng
from concurrent import futures
import numpy as np

print(ng.__file__)


def sqrt(x):
    return np.sqrt(x)

num_weights = 50
num_workers = 50
# Set up the optimizer
optimizer = ng.optimizers.CMA(parametrization=num_weights, budget=1000000, num_workers=num_workers)

counter = 0
def model_eval(x):
    global counter
    counter += 1
    if int(sqrt(counter)) != int(sqrt(counter+1)):
        print(counter)
    return sum(x**2)

with futures.ThreadPoolExecutor(max_workers=optimizer.num_workers) as executor:
    recommendation = optimizer.minimize(model_eval, executor=executor, batch_mode=True)
========

I get no error.
I close the issue, please feel free to post the exact code if you still get an error. However, the message you get does not come from Nevergrad.
