### ISSUE TITLE
Non-reproducible results with CMA

### ISSUE THREAD

**Issue by lazyoracle** [facebookresearch/nevergrad#161]
## Steps to reproduce

  1. Optimize a function using the `CMA` algorithm
  2. Run the same optimization multiple times and log results

## Observed Results

  * Different runs return different recommendation results

## Expected Results

  * Consistent results since my assumption was that `nevergrad` sets the seed for the optimizer internally since that is not provided in the interface.

## Suggestion

  * Closer inspection reveals that `CMA` is seeded with `np.nan` in `nevergrad` which doesn't ensure that identical results get returned from `CMA`. Is this a conscious decision? Are there plans to have an optional `seed` variable available during initializing the optimizers? If not, I suggest we set the `seed` for `CMA` to something that ensures consistent results.

## Relevant code

Code snippet from [`optimizerlib.py`](https://github.com/facebookresearch/nevergrad/blob/master/nevergrad/optimization/optimizerlib.py#L168):

```
class _CMA(base.Optimizer):
    ...

    @property
    def es(self) -> cma.CMAEvolutionStrategy:
        if self._es is None:
            popsize = max(self.num_workers, 4 + int(3 * np.log(self.dimension)))
            diag = self._parameters.diagonal
            self._es = cma.CMAEvolutionStrategy(x0=np.zeros(self.dimension, dtype=np.float),
                                                sigma0=self._parameters.scale,
                                                inopts={"popsize": popsize, "seed": np.nan, "CMA_diagonal": diag})
        return self._es

```

**Comment by lazyoracle** [comment]
Resolved by setting the seed to `numpy.random` before initializing the optimizer.
```
import numpy as np
np.random.seed(0)
```

**Comment by jrapin** [comment]
CMA is indeed seedable in the latest versions, and this is tested in test_optimizerlib.py (test_optimizers_recommendation).
However, following #4, I am still ensure what is the best way to handle randomness. I am not in favor of providing extra arguments. I am thinking of adding an extra `random_state` attribute for the optimizer base class, and pulling random numbers from there in all optimizers.
