### ISSUE TITLE
Constraints do not work

### ISSUE THREAD

**Issue by sergeiiudin** [facebookresearch/nevergrad#1656]
## Steps to reproduce

  1. Define the objective: 
```
    def obj(x):
        return -(x[0] + x[1] + x[2])
```

  2. Define 1 simple constraint:

```
    def cons(x):
        return x[2]
```

  3. Define binary grid of parameters and budget: 

```
    s = ng.p.Array(shape=(3,)).set_bounds(0, 1).set_integer_casting()
    b = 1000
```
  
  4. Minimize the objective w.r.t. constraint: 

```
    opt = ng.optimizers.NGOpt(parametrization=s, budget=b)
    rec = opt.minimize(obj, constraint_violation=[cons])
```

## Observed Results

  rec.loss is -3.0 for some reason, and constraint is violated

## Expected Results

  rec.loss is -2.0 and x[2] == 0, constraint is not violated

**Comment by sergeiiudin** [comment]
Yes, I have posted it by error:) Now I've updated the issue description. The bug is with the last release version, 1.0.5. I did not observe such behaviour, if use cheap constraints.

**Comment by teytaud** [comment]
Your remark is excellent.
I bring a fix.
In the mean time, you might pick the best so far among points which do not violate constraints and it will work (basically the optimization works, just "recommend" fails).
I bring the fix asap.

**Comment by teytaud** [comment]
https://github.com/facebookresearch/nevergrad/pull/1657

**Comment by teytaud** [comment]
Will push nevergrad 1.07 asap

**Comment by teytaud** [comment]
This is a correct fix I think (not yet in Pypi, will do asap).

**Comment by sergeiiudin** [comment]
Thank you! Now it works.

**Comment by teytaud** [comment]
It's in 1.0.8 https://pypi.org/project/nevergrad/

@sergeiiudin  thanks a lot. You have found a strong issue in a release.

I'll investigate a bit more later; the new version was done quickly, maybe I can do some things better.
