### ISSUE TITLE
RuntimeError("Only one call can be registered at a time") with RBO

### ISSUE THREAD

**Issue by robert1826** [facebookresearch/nevergrad#179]
## Steps to reproduce

  1. install nevergrad-0.2.0
  2. initialize a RBO optimizer with small budget (I used 10 in this case)
  3. run optimization
  
- note that this happens randomly so sometimes I run and get no errors

## Observed Results

```
Traceback (most recent call last):
  File ".\mnist.py", line 51, in <module>
    recommendation = optimizer.optimize(ifunc)
  File "C:\Users\robert\AppData\Local\Programs\Python\Python36\lib\site-packages\nevergrad\optimization\base.py", line 402, in optimize
    self.tell(x, job.result())
  File "C:\Users\robert\AppData\Local\Programs\Python\Python36\lib\site-packages\nevergrad\optimization\base.py", line 244, in tell
    self._internal_tell_candidate(candidate, value)
  File "C:\Users\robert\AppData\Local\Programs\Python\Python36\lib\site-packages\nevergrad\optimization\base.py", line 328, in _internal_tell_candidate
    self._internal_tell(candidate.data, value)
  File "C:\Users\robert\AppData\Local\Programs\Python\Python36\lib\site-packages\nevergrad\optimization\optimizerlib.py", line 1025, in _internal_tell
    self._fake_function.register(y, -value)  # minimizing
  File "C:\Users\robert\AppData\Local\Programs\Python\Python36\lib\site-packages\nevergrad\optimization\optimizerlib.py", line 967, in register
    raise RuntimeError("Only one call can be registered at a time")
```

## Expected Results

  There should be no errors running the optimization

## Relevant Code

  ```
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

from nevergrad.optimization import optimizerlib
from nevergrad import instrumentation as instru
from nevergrad.optimization import base

X, y = load_digits(return_X_y=True)
Xtrain, XTest, yTrain, yTest = train_test_split(X, y, random_state=42)

print('training with {} examples, testing with {}'.format(len(Xtrain), len(XTest)))

def train_and_score(args):
    if args['C_in'] > 0:
        model = SVC(C=args['C_in'], kernel=args['kernel_in'], degree=args['degree_in'])
        model.fit(Xtrain, yTrain)
        res = model.score(XTest, yTest)
    else:
        res = 1000
    
    if res > 0.98 and res < 1:
        print('args: {}'.format(args), end=', ')
        print('res: {}'.format(res))
    return -res

def train_and_score_wrapper(C_in, kernel_in, degree_in):
    return train_and_score({'C_in':C_in, 'kernel_in':kernel_in, 'degree_in':degree_in})

kernel_in = instru.variables.SoftmaxCategorical(['linear', 'poly', 'rbf', 'sigmoid'])
C_in = instru.variables.Gaussian(mean=1, std=2)
degree_in = instru.variables.OrderedDiscrete(list(range(1, 10)))
ifunc = instru.InstrumentedFunction(train_and_score_wrapper, C_in, kernel_in, degree_in)

optimizer = optimizerlib.RBO(instrumentation=ifunc.dimension, budget=10, num_workers=1)
recommendation = optimizer.optimize(ifunc)
print(recommendation)

  ```

**Comment by robert1826** [comment]
This might be properly reproducible by adding:
```
import numpy as np
np.random.seed(1)
```
to the above mentioned code

**Comment by jrapin** [comment]
Hi,
Thanks for pointing out and for the details. This is indeed completely unexpected.
I will try to understand and fix this asap but am quite busy for the following week :s Don't hesitate to propose a fix if you were able to solve it ;)

**Comment by jrapin** [comment]
This error is pretty weird, since the underlying BO algorithms seems to ask twice for the same point, which should not happen in my understanding. I implemented a fix to prevent nevergrad from raising an error in this case.

On a side note, I think using `SoftmaxCategorical` with BO is a bit dangerous here since BO assumes the function is deterministic, while `SoftmaxCategorical` adds some randomness to the evaluation since the parameters are sampled randomly. I asked confirmation to my colleage who is more knowledgeable than me about it (see #185)

**Comment by jrapin** [comment]
This should now be solved (though in a hacky way), please reopen this task or another if you still encounter any issue ;) and be careful with `BO` when using `SoftmaxCategorical`, it may indeed lead to very bad results :s

**Comment by robert1826** [comment]
Alright .. thanks a lot for solving the problem and the hints too :)

**Comment by robert1826** [comment]
> This error is pretty weird, since the underlying BO algorithms seems to ask twice for the same point, which should not happen in my understanding. I implemented a fix to prevent nevergrad from raising an error in this case.
> 
> On a side note, I think using `SoftmaxCategorical` with BO is a bit dangerous here since BO assumes the function is deterministic, while `SoftmaxCategorical` adds some randomness to the evaluation since the parameters are sampled randomly. I asked confirmation to my colleage who is more knowledgeable than me about it (see #185)

I don't know the specific implementation but upon trying to debug the issue I noticed that the suggested candidate data change but the args stay the same ... so maybe the instrumentation is the issue here

**Comment by jrapin** [comment]
Depending on your instrumentation, same args for different data can be normal (when mapping a continuous variable to a discrete one with `SoftmaxCategorical` or `OrderedDiscrete`) and different args can also come from the same data (`SoftmaxCategorical` is stochastic).

Concerning the interface with `bayes_opt` we'll discuss in #189 ;)
