### ISSUE TITLE
Documentation is out of date for 0.2.0

### ISSUE THREAD

**Issue by dsblank** [facebookresearch/nevergrad#187]
Trying to run examples like:

https://github.com/facebookresearch/nevergrad/blob/master/docs/machinelearning.md

gives errors.

**Comment by jrapin** [comment]
Thank you for pointing out, I indeed forgot to update this document. I'll take care of it asap ;)

**Comment by jrapin** [comment]
Should be better now, let us now if you run into other problems ;)
