### ISSUE TITLE
Documentation on functions

### ISSUE THREAD

**Issue by lazyoracle** [facebookresearch/nevergrad#193]
## Expected Results
Nevergrad includes a pretty comprehensive list of implemented functions to test algorithms on. However, is it possible to include some documentation to the functions implemented inside `corefuncs.py` regarding the nature of these functions (multimodal, monotonous etc.)? If not some detailed documentation of the function properties, at least a link to some white paper/publication from where the functions are sourced (any of the past CECs? Since nevergrad is organising a competition in CEC19)?
  
## Relevant Code

  ```
from nevergrad.functions.corefunc import registry as func_registry
print(sorted(func_registry.keys()))
  ```

**Comment by jrapin** [comment]
@teytaud will try to provide more information.
However, what would be the best way to document this? I would go for docstrings, but it may not be that easy to access?

**Comment by lazyoracle** [comment]
What is the long-term plan for generating documentation for nevergrad? Docstrings that compile using Sphinx as usual? For now, since most of the Nevergrad user community is typically comfortable with diving deep into source codes, plain docstrings should be fine I presume.

**Comment by teytaud** [comment]
Pushed. Criticisms welcome :-)

**Comment by jrapin** [comment]
Concerning documentation, on the long run, sphynx generated doc is the aim indeed. I am happy with delaying this a bit for now though :D

**Comment by lazyoracle** [comment]
> 
> 
> Pushed. Criticisms welcome :-)

@teytaud Is it possible to find the source of these functions in literature? Were these part of some other benchmarking suite/competition/publication? In particular `deceptiveillcond`, `deceptivemultimodal` and `deceptivepath`. Would be good to see how they were arrived at and also to cite the original source in future publications.

**Comment by teytaud** [comment]
The deceptive functions are new. They are introduced in the paper "Openly Revisiting Derivative-Free Optimization" this year at Gecco'19, Prag. There is a competition related to it in https://github.com/facebookresearch/nevergrad/blob/cec2019/docs/CEC2019.md .

**Comment by teytaud** [comment]
+I add in my TODO-list the need for more detailed doc.

**Comment by lazyoracle** [comment]
@teytaud As per the definition in `corefuncs.py`, [deceptivepath](https://github.com/facebookresearch/nevergrad/blob/830a07280431100d6e79721dfd854a7f912dffd4/nevergrad/functions/corefuncs.py#L202) and [deceptivemultimodal](https://github.com/facebookresearch/nevergrad/blob/830a07280431100d6e79721dfd854a7f912dffd4/nevergrad/functions/corefuncs.py#L218) are essentially the same function? Is this how it is intended to be?
