### ISSUE TITLE
TwoPointsDE doesn't make use of "told" points

### ISSUE THREAD

**Issue by robert1826** [facebookresearch/nevergrad#195]
## Steps to reproduce

  1. Install Nevergrad
  2. Run TwoPointsDE optimization on any problem and record the params used and the values produces
  3. Terminate the script
  4. Reload the script and for each previously recorded arg, call optimizer.tell(cand, value)
  5. Ask optimizer for new points

## Observed Results

optimizer returns same initial points (same seed used) without taking into consideration the previously recorded args / points and values

## Expected Results

the optimizer should provide new points for evaluation and take into consideration the previously evaluated points

**Comment by robert1826** [comment]
I took some time trying to debug the issue and I came across this line: https://github.com/facebookresearch/nevergrad/blob/5a4d901ed2e1d09dbb4952ac42b92ca09322db6f/nevergrad/optimization/differentialevolution.py#L171 which suggests that there is a bug that simply the provided candidate and value is not registered as a particle.

I think this should be easily fixable by:
`particle = DEParticle(position=candidate.data, fitness=value) `

**Comment by jrapin** [comment]
Thank you for spotting it and solving it ;)
