### ISSUE TITLE
How to specify which varaible to minimize over and which just for completeness of the function

### ISSUE THREAD

**Issue by eglxiang** [facebookresearch/nevergrad#232]
And how to initialize ng.var.Array( )?

**Comment by jrapin** [comment]
Hi,
Concerning `Array`, I've tried to be more explicit as to the parameters of the different variables (see [here](https://github.com/facebookresearch/nevergrad/blob/master/docs/instrumentation.md#variables)): the parameters are the dimensions of the data you want to optimize upon: for an array of shape `(2, 3)` you would initialize as `Array(2, 3)`.

Concerning variables to minimize over or not, there is an example here [here](https://github.com/facebookresearch/nevergrad/blob/master/docs/instrumentation.md#instrumentation-1): you can specify anything to the `Instrumentation` initialization, if it is not of type `Variable` then it will be considered as constant and not minimized upon (`"blublu"` in the example).

Is it clearer? The documention is still patchy, at some points we'll make a nicer version of it. It the meantime please let me know if anything is still not clear (and you are also of course welcome to propose changes if you want ;) )

**Comment by eglxiang** [comment]
Thanks, they're much more clear now!
