### ISSUE TITLE
Simplify visualization

### ISSUE THREAD

**Issue by jrapin** [facebookresearch/nevergrad#266]
We should add a visualization tool to help understand the behavior of the function with regard to its arguments.
In my opinion, good example of such visualization is: https://bl.ocks.org/syntagmatic/482706e0638c67836d94b20f0cb37122

Other ideas are more than welcome ;)

**Comment by jrapin** [comment]
More to come soon.

**Comment by CavalloneChen** [comment]
Are you planning to use D3?

**Comment by jrapin** [comment]
Not directly. The plan is to interface nicely with [hiplot](https://ai.facebook.com/blog/hiplot-high-dimensional-interactive-plots-made-easy/) for parallel coordinate plots. It's already mostly compatible, what is missing is the doc...

**Comment by jrapin** [comment]
Done through https://github.com/facebookresearch/nevergrad/blob/cd7bd374e33bd39dcd4907b890429e6e5b42ad29/nevergrad/optimization/callbacks.py#L48
