### ISSUE TITLE
Reference for TBPSA?

### ISSUE THREAD

**Issue by ytsaig** [facebookresearch/nevergrad#273]
Are any references for the TBPSA optimizer? In [the benchmark results](https://github.com/facebookresearch/nevergrad/blob/master/docs/benchmarks.md) it produces competitive results, and I found it to be quite effective as well in experiments. However I could not find a reference for it. 

Specifically, I'm wondering about the following choices: In [the implementation](https://github.com/facebookresearch/nevergrad/blob/master/nevergrad/optimization/optimizerlib.py#L515) it keeps track of the `_loss_record` for each candidate and once enough samples have been collected, a 2-sample t-stat for the difference in means of the first and last fifths of `_loss_record` is calculated and stored in `z`. 
* Since `_loss_record` is not sorted as far as I can tell, what's the motivation for using the first and last fifths of the data?
* What the motivation for using the constants `2` and `0.84` to scale `mu`?

Thanks!

**Comment by teytaud** [comment]
Motivation for using the first and last fifth: it's sorted by time, so this is the measure of whether the population size is enough for a stable convergence.

Motivation for using the constants 2 and 0.84: these constants are classical in other fields of evolutionary computation for parameter adaptation, namely the (1+1)-ES with one-fifth rule. However, it's true that there is no clear reason why the same values would be good here.

References:

- this is an adaptation from population control, originally published in https://homepages.fhv.at/hgb/New-Papers/PPSN16_HB16.pdf; we did a different test for convenience, but the principle is the same

- probably first use of this exact algorithm: https://www.lamsade.dauphine.fr/~cazenave/papers/games_cec.pdf
@inproceedings{tbpsa,
title={Parallel Noisy Optimization in Front of Simulators:
Optimism, Pessimism, Repetitions Population
Control},
author={T. Cazenave, M. Oquab, J. Rapin, O. Teytaud},
year={2019},
booktitle={proceedings of CEC 2019 workshops},
url={https://www.lamsade.dauphine.fr/~cazenave/papers/games_cec.pdf}}

**Comment by ytsaig** [comment]
@teytaud thanks for the clarifications and references! The second reference seems quite useful in general since it covers many of the optimizers implemented in the library, you might consider adding it to the README.
