### ISSUE TITLE
Keep args and kwargs in archive

### ISSUE THREAD

**Issue by jrapin** [facebookresearch/nevergrad#290]
Args and kwargs can be useful for visualization and for keeping the actual best point

**Comment by jrapin** [comment]
archive may also need to be converted to a list instead, keeping only best candidates

**Comment by teytaud** [comment]
There is all the information in the archive, right ? so that what we need is just accessors ?

**Comment by jrapin** [comment]
> There is all the information in the archive, right ? so that what we need is just accessors ?

not exactly true: we have the standardized data in the archive, but not args and kwargs, and the process to obtain them is not deterministic (`Choice`/`SoftmaxCategorical`)
