### ISSUE TITLE
Adding COCO inside Nevergrad ?

### ISSUE THREAD

**Issue by teytaud** [facebookresearch/nevergrad#327]
(from discussion with Dimo)
Maybe we can include COCO easily:

(1)  doc is https://coco.gforge.inria.fr/apidocs-cocoex/cocoex.Suite.html#get_problem_by_function_dimension_instance

(2) loop on test functions is

>>> import cocoex as ex
>>> suite = ex.Suite("bbob-biobj", "", "")
>>> observer = ex.Observer("bbob-biobj", "result_folder:doctest")
>>> for fun in suite:
...     if fun.index == 0:
...         print("Number of objectives %d, %d, %d" %
...                 (fun.number_of_objectives,
...                  suite.number_of_objectives[0],
...                  suite.number_of_objectives[-1]))
...     assert fun.evaluations == 0
...     assert fun.number_of_objectives == suite.number_of_objectives[0]
...     # run run run using fun  # doctest: +ELLIPSIS

(3) is it a good idea ?

(a) compared to just downloading Coco and running all nevergrad optimizers there, the drawback is that you don't get the data in Coco format

(b) compared to  just downloading Coco and running all nevergrad optimizers there, the advantage is that all algorithms are included, you can reproduce everything

**Comment by CavalloneChen** [comment]
This would be very helpful.

**Comment by teytaud** [comment]
We added yabbob. I Will therefore close this issue. Please reopen if necessary. @CavalloneChen
