### ISSUE TITLE
better accessor to Optimizer.archive ?

### ISSUE THREAD

**Issue by teytaud** [facebookresearch/nevergrad#329]
(also from discussion with Dimo)

## Steps to reproduce

do an optimizer run

## Observed Results

optimizer.recommend()   provides a good x, but not its f(x).

## Expected Results

better accessibility of the archive 

## Relevant Code

"optimizer.archive" exists in the class Optimizer in base.py; but there is no easy accessor to it.
In particular about the best point.

**Comment by vondele** [comment]
also, for noisy functions, the best estimate known to the optimizer for f(x_{opt}) might be different from any of the evaluated f(x_i).  It would be useful to have access to this estimate.

**Comment by teytaud** [comment]
@vondele  there is the function recommend for that. We designed yabbob and variants (in particular yanoisybbob) precisely because the noisy coco/bbob was not dealing properly with noise.

**Comment by teytaud** [comment]
I would say that current_best solves this. Reopen if necessary.@vondele
