### ISSUE TITLE
MPCEDA not updating recommendation

### ISSUE THREAD

**Issue by ARF1** [facebookresearch/nevergrad#349]
I have been running a comparison of the learning curves of all available algorithms on one of my problems.

While doing so, I believe I have stumbled across a bug: It appears the MPCEDA algorithm does not update its recommendation:

```
Running algorithm "MPCEDA" in iteration 0. Elapsed time: 0.0 minutes
Iteration: 100 - R: 0.0 - R recommendation: -12.44270317575601 - R validation: 1.7109912670091658
Iteration: 200 - R: -12.44270317575601 - R recommendation: -12.44270317575601 - R validation: 1.7109912670091658
Iteration: 300 - R: -12.44270317575601 - R recommendation: -12.44270317575601 - R validation: 1.7109912670091658
Iteration: 400 - R: -12.44270317575601 - R recommendation: -12.44270317575601 - R validation: 1.7109912670091658
Iteration: 500 - R: -5.226382018818163 - R recommendation: -12.44270317575601 - R validation: 1.7109912670091658
Iteration: 600 - R: -0.20125490416823116 - R recommendation: -12.44270317575601 - R validation: 1.7109912670091658
Iteration: 700 - R: -4.537591667629572 - R recommendation: -12.44270317575601 - R validation: 1.7109912670091658
```

Note: In the above log, I am maximizing the value of R. (Or more precisely minimizing the value of -R.)

So, despite having achieved a solution with R=-0.2 at least once, the recommendation still provides a solution that leads to R=-12.4.

Version used:
```
C:\Users\My User>conda list nevergrad
# packages in environment at Z:\\Miniconda3\envs\nevergrad_test:
#
# Name                    Version                   Build  Channel
nevergrad                 0.2.3                    pypi_0    pypi
```

**Comment by teytaud** [comment]
Actually this is not a bug; but possibly a bad feature.
MPCEDA, like all EDA in Nevergrad, does not recommend the best so far but the center of the current distribution.

This is better in noisy settings, and in noise-free settings for some clearly convex functions.
As MPCEDA is aimed at doing noisy optimization, it looks like a reasonable choice.
However, experiments show that noisy optimization algorithms can be great in difficult noise-free optimization - except that they should use a naive recommendation, i.e. recommend the best so far.

For TBPSA, we therefore do a "naiveTBPSA"; which is equivalent to TBPSA, except that the recommendation is the best so far.

I can add a NaiveMPCEDA ?

**Comment by teytaud** [comment]
I propose pull request https://github.com/facebookresearch/nevergrad/pull/351

**Comment by ARF1** [comment]
@teytaud Thanks for the explanation. I really like this library but as non-expert in optimization, I am struggling to apply it effectively.

While a large number of algorithms is provided, their documentation is largely non-existent. I would really welcome a page which describes the essentials of the algorithms and maybe classifies them broadly. I found it very useful that in SciPy the documentation often contains a link to the paper in which the algorithm was proposed.

Though I understand that writing such documentation is probably a horribly tedious and boring job for those who know the algorithms well enough to actually implement them...
