### ISSUE TITLE
'Instrumentation' object has no attribute 'set_cheap_constraint_checker'

### ISSUE THREAD

**Issue by yutongyan** [facebookresearch/nevergrad#353]
## Observed Results

  * 'Instrumentation' object has no attribute 'set_cheap_constraint_checker'
## Expected Results

  * What did you expect to happen?

## Relevant Code

  ```
  // TODO(you): code here to reproduce the problem
  ```
import nevergrad as ng

def square(x):
    return sum((x - .5)**2)
optimizer = ng.optimizers.OnePlusOne(instrumentation=2, budget=100)
optimizer.instrumentation.set_cheap_constraint_checker(lambda x: x[0] >= 1)
recommendation = optimizer.minimize(square)
print(recommendation)  # optimal args and kwargs

**Comment by Corwinpro** [comment]
What is your `nevergrad` version? It might be that it is outdated.
```
import nevergrad
print(nevergrad.__version__)
```

**Comment by yutongyan** [comment]
@Corwinpro My version is 0.2.3. I installed via pip.

**Comment by Corwinpro** [comment]
@yutongyan Apparently it is outdated. Install with `pip install git+https://github.com/facebookresearch/nevergrad@master#egg=nevergrad`.

**Comment by yutongyan** [comment]
@Corwinpro Thank you! It worked.
