### ISSUE TITLE
Code Understanding Question for `optimizerlib.py`'s PCEDA(EDA): Potential Minor/Unimportant Bug?

### ISSUE THREAD

**Issue by thomasWeise** [facebookresearch/nevergrad#354]
Dear Colleagues.

I was just randomly flipping through some code here in order to get an understanding on how nevergrad works and also to refresh my Python. So, please keep in mind: I have little to none understanding of that.
I just came across [line 340](https://github.com/facebookresearch/nevergrad/blob/master/nevergrad/optimization/optimizerlib.py#L340) of optimizerlib.py, where it says:

  ```
        if len(self.archive_fitness) >= 5 * self.llambda:
            first_fifth = [self.archive_fitness[i] for i in range(self.llambda)]
            last_fifth = [self.archive_fitness[i] for i in range(4 * self.llambda, 5 * self.llambda)]
  ```

So this is probably wrong and also unimportant, but, since I saw it:
If `len(self.archive_fitness)` would be greater than `5 * self.llambda`, then the "last fifth" would not be `range(4 * self.llambda, 5 * self.llambda)`, but `range(len(self.archive_fitness)- self.llambda + 1, len(self.archive_fitness))`, I think (?)
Of course, it could be that `len(self.archive_fitness)` cannot actually exceed `5 * self.llambda`, in which case the above does not matter.

Cheers,
   Thomas.

**Comment by teytaud** [comment]
Hello and thanks! I think the code is actually correct.
We are interested in the first and last fifth among the most recent 5*lambda points.
So 1:lambda, and 4lambda:5lambda.

**Comment by thomasWeise** [comment]
OK, I get it ^_^: `len(self.archive_fitness)` will never actually be greater than `5 * self.llambda`, but may at most equal exactly `5 * self.llambda`.

**Comment by Corwinpro** [comment]
It is great you could find this, @thomasWeise . Maybe it is worth adding a little docstring explaining this?
Don't think it's quite true that "`len(self.archive_fitness)` will never actually be greater than `5 * self.llambda`". It might be that `len(self.archive_fitness)` can be greater than `5 * self.llambda`, but apparently we only care about its first `5 * self.llambda` elements.

**Comment by thomasWeise** [comment]
I see. Thank you ^_^
