### ISSUE TITLE
Error when calling provide_recommendation() too early

### ISSUE THREAD

**Issue by brockho** [facebookresearch/nevergrad#444]
## Steps to reproduce

Create any `scipy.optimize` algorithm from within Nevergrad and ask for a recommendation before the first `ask()` call. With `ng.optimizers.OnePlusOne` on the contrary, `provide_recommendation` returns the initial point as expected.

## Observed Results

Compared to Nevergrad-internal algorithms (like `ng.optimizers.OnePlusOne`), the algorithms obtained from `scipy.optimize` do not allow to get a recommendation before the first `ask()`. I get an `AssertionError: Optimization was not even started` with the current version (Nevergrad 0.3.0, Windows laptop with Anaconda Python 3).

## Expected Results

Similar to the `ng.optimizers.OnePlusOne` above, a recommendation before the first `ask()` should be the initial `x0`.

## Relevant Code

  ```python
In [1]: import nevergrad as ng
In [2]: sqp = ng.optimizers.SQP(instrumentation=2, budget=100)
In [3]: sqp.provide_recommendation()
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-7-b54262d49671> in <module>
----> 1 s.provide_recommendation()

~\Anaconda3\lib\site-packages\nevergrad\optimization\base.py in provide_recommendation(self)
    435             on the function (`objective_function(*candidate.args, **candidate.kwargs)`).
    436         """
--> 437         return self.recommend()  # duplicate method
    438
    439     def recommend(self) -> Candidate:

~\Anaconda3\lib\site-packages\nevergrad\optimization\base.py in recommend(self)
    446             on the function (`objective_function(*candidate.args, **candidate.kwargs)`).
    447         """
--> 448         return self.create_candidate.from_data(self._internal_provide_recommendation(), deterministic=True)
    449
    450     def _internal_tell_not_asked(self, candidate: Candidate, value: float) -> None:

~\Anaconda3\lib\site-packages\nevergrad\optimization\recaster.py in _internal_provide_recommendation(self)
    233         else the best pessimistic point.
    234         """
--> 235         assert self._messaging_thread is not None, 'Optimization was not even started'
    236         if self._messaging_thread.output is not None:
    237             return self._messaging_thread.output  # type: ignore

AssertionError: Optimization was not even started
```

But:
```python
In [4]: one = ng.optimizers.OnePlusOne(instrumentation=2, budget=100)
In [5]: one.provide_recommendation()
Out[5]: Candidate(args=(array([0., 0.]),), kwargs={}, data=[0. 0.])
```

Also after the first `ask()` call, things look right for the `scipy.optimize` algos:
```
In [6]: anewsqp = ng.optimizers.SQP(instrumentation=2, budget=100)
In [7]: offspring = anewsqp.ask()
In [8]: anewsqp.provide_recommendation()
Out[8]: Candidate(args=(array([0., 0.]),), kwargs={}, data=[0. 0.])
```

**Comment by jrapin** [comment]
Hi @brockho 
Thanks for pointing out! Do you want to try to solve this yourself? ;) Doing this means adding a test in nevergrad/optimization/test_recaster.py (basically exactly what you've just written), and updating the code in recaster.py to send zero instead of raising the error.
If you don't, I can try to do it tomorrow ;)

**Comment by teytaud** [comment]
I think the fix is as follows:
(1) removing the assert that is raised in that case
(2) replace it by something like:
       if self._messaging_thread is None: # 'Optimization was not even started'
            return self.current_bests["pessimistic"].x

@jrapin  ok for you ?
@brockho  thanks for pointing out the issue.

**Comment by jrapin** [comment]
@teytaud brockho already started implementing a fix for this. @brockho do you want me to update the PR so that it pass all the tests, or do you want to do it yourself?
