### ISSUE TITLE
Could not find the exact reference for PSO algorithm SPSO2011

### ISSUE THREAD

**Issue by jiweiqi** [facebookresearch/nevergrad#447]
https://github.com/facebookresearch/nevergrad/blob/5bc5d705524edce57437bcd37795efd01e3d7362/nevergrad/optimization/optimizerlib.py#L628

**Comment by jrapin** [comment]
@teytaud any more information?

**Comment by teytaud** [comment]
Sorry for the delay, here you are: https://ieeexplore.ieee.org/document/6557848

PSO performed surprisingly well in some cases whereas none of us was an expert, this was just a fast but successful developments - variants of our PSO are more than welcome in the platform, we might have been suboptimal.
