### ISSUE TITLE
Gaussian variables vs affined Array

### ISSUE THREAD

**Issue by Corwinpro** [facebookresearch/nevergrad#453]
## Steps to reproduce

I investigated the behaviour of two types of variables. The first type is an `Array` variable of dimension* `(2, 2)`. The second type is a Gaussian variable with `shape = [2, 2]`.

I noticed that these two definitions are quite similar:

```
array_variable = ng.var.Array(2, 2).affined(2, 10)
array_variable.data_to_arguments([-2.0, 2.0, -2.0, 2.0])
```
and for the `Gaussian`:
```
gaussian_variable = ng.var.Gaussian(10, 2, [2, 2])
gaussian_variable.data_to_arguments([-2.0, 2.0, -2.0, 2.0])
```

The outputs of the both of the scripts are:
```
>>> ((array([[ 6., 14.],
>>>         [ 6., 14.]]),), {})
```

## Observed Results

It seems that these two definitions are somewhat identical. That would definitely be true,  if the internal `data` attribute of the nevergrad's `Variable` is normally distributed.

## Possible issue

- Is it correct that defining a `Gaussian` variable is equivalent to defining a `Array().affined()`?
- If no, could we please specify the difference? I could create a small docstring update for this, explaining the difference. 
- If yes, In which cases it is then preferred to use them? And
- Does the current implementation introduce some sort of an ambiguity in terms of defining a variable with gaussian prior?

Thank you in advance.

**Comment by jrapin** [comment]
Both are equivalent (it's somehow [lost in the doc](https://github.com/facebookresearch/nevergrad/blob/master/docs/instrumentation.md#variables), not very explicitely).
`Gaussian` was the initial variable we were using, and we created `Array` to generalize it, so `Array` should basically always be preferred.

Also with #323 #391 #440 `Gaussian` will come to disappear, and `Array` will change API for more clarity ([see here](https://www.facebook.com/notes/nevergrad-users/moving-to-new-parametrization-upcoming-unstability-and-breaking-changes/639090766861215/))

**Comment by Corwinpro** [comment]
Thank you very much, @jrapin !
