### ISSUE TITLE
Small hacks that could be quite impactful

### ISSUE THREAD

**Issue by teytaud** [facebookresearch/nevergrad#466]
1. Rescaling in oneshot optimization

There is a formula for rescaling oneshot optimizer in:
https://github.com/facebookresearch/nevergrad/blob/fa0df1df70240559c6b500590ead1184d7c8b5f3/nevergrad/optimization/rescaledoneshot.py

Maybe we could test several formulas, instead of just one.
Autorescale should be a string instead of a boolean, and ideas for good formulas.

2. Yasmallbbob

We have variants of yabbob such as yanoisybbob, yaparabbob, yahdbbob, yabigbbob. Maybe we need yasmallbbob, like yabigbbob but with small budget instead of big budget.

4. "Exporttable" creates latex code; exporting in a directly readable format could be cool (csv? )

5. More technical: create a duplicate of "discrete" and "discrete2" in experiments.py  so that we use instrumented functions (harder for newcomers than others, in terms of coding).

6. Yaoneshotbbob and 7. Yafewshotsbbob

We have variants of yabbob such as yanoisybbob, yaparabbob, yahdbbob, yabigbbob. Maybe we need yaoneshotbbob, like yaparabbob but with numworkers equal To the budget.
 
Fewshots (numworkers=budget/4) could be cool as Well.

**Comment by thesickcynic** [comment]
Hi. I'd like to take up issue 4 out of these, to export to CSV.

**Comment by jrapin** [comment]
Hi @thesickcynic,
Thank you for your The file is [here](https://github.com/facebookresearch/nevergrad/blob/master/nevergrad/benchmark/exporttable.py)
If I'm correct, the aim is to remove this code, and build a pd.DataFrame instead, which can be dumped to csv **and** exported to latex, so all the code there should be removed eventually. @teytaud do you agree?
How would you like to proceed? You can open a specific issue if you want to discuss more, or you can propose a PR and we con iterate on that.

**Comment by thesickcynic** [comment]
So the expected behaviour would be for `export_table()` to take in the values, store them in a `pd.DataFrame`, and then use something like Panda's `to_csv()` and `to_latex()` to write to CSV and Latex respectively? And the function should always store to both CSV and Latex?

**Comment by jrapin** [comment]
That would work yes,
It may actually only require like 3 lines of code instead of the all function

**Comment by growupboron** [comment]
I will like to work on these, any of these, still up for grabs?

**Comment by jrapin** [comment]
@teytaud what would you advise?

**Comment by teytaud** [comment]
Sounds like this is solved.
New tasks posted in nevergrad users.
I apologize for being so late for posting here.
