### ISSUE TITLE
Can't do ng.p.Array.set_bounds using numpy arrays

### ISSUE THREAD

**Issue by drivkin** [facebookresearch/nevergrad#482]
## Steps to reproduce

  1. Try to create a ng.p.Array and then set its bounds using numpy arrays (see code below)

BTW I am using version 0.3.1

## Observed Results
Traceback (most recent call last):
  File "logs/nevergrad_bug.py", line 9, in <module>
    arr.set_bounds(low, high)
  File "/usr/local/lib/python3.7/dist-packages/nevergrad/parametrization/data.py", line 216, in set_bounds
    std_bounds = tuple(self._to_reduced_space(b) for b in self.bounds)  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/nevergrad/parametrization/data.py", line 216, in <genexpr>
    std_bounds = tuple(self._to_reduced_space(b) for b in self.bounds)  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/nevergrad/parametrization/data.py", line 299, in _to_reduced_space
    value = self.bound_transform.backward(value)
  File "/usr/local/lib/python3.7/dist-packages/nevergrad/parametrization/transforms.py", line 187, in backward
    if (self.a_max is not None and np.max(y) > self.a_max) or (self.a_min is not None and np.min(y) < self.a_min):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## Expected Results

  *  Set bounds without failing

## Relevant Code

  ```
import nevergrad as ng
import numpy as np

init_value = np.ones(3)
low = np.zeros(3)
high = 2*np.ones(3)

arr = ng.p.Array(init=init_value)
arr.set_bounds(low, high)
  ```

**Comment by jrapin** [comment]
Hi,
Thanks for pointing out. I happened to stumble on the same issue today, and included a fix in #471 .
I was not planning on landing this soon though: it relies on the major PR #459 that we are currently testing, and before which we will release 0.3.2, so not included before 0.3.3.
If you need it though I can probably backport it somehow.

**Comment by jrapin** [comment]
Actually, the fix will be part of version 0.3.2 which will include #459 I was wrong yesterday. Hopefully we can land this within a week time at most.

**Comment by drivkin** [comment]
Great! Thanks. Would you like me to close the issue?

**Comment by jrapin** [comment]
No please leave it on as long as it's not working (merging #471 will automatically close it)

**Comment by drivkin** [comment]
Sounds good

**Comment by jrapin** [comment]
Then again... after discussing with @teytaud , we'll merge today into master so it's gonna be closed soon. And if everything goes well we will release v0.3.2 early next week.

**Comment by jrapin** [comment]
Closing since it didnt close automatically. It does seem solve ;)
```
Python 3.7.5 (default, Oct 22 2019, 10:35:10)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import nevergrad as ng
   ...: import numpy as np
   ...:
   ...: init_value = np.ones(3)
   ...: low = np.zeros(3)
   ...: high = 2*np.ones(3)
   ...:
   ...: arr = ng.p.Array(init=init_value)
   ...: arr.set_bounds(low, high)
/Users/jrapin/fairinternal/dfoptim/nevergrad_repository/nevergrad/parametrization/data.py:223: UserWarning: Bounds are 2.0 sigma away from each other at the closest, you should aim for at least 3 for better quality.
  warnings.warn(f"Bounds are {min_dist} sigma away from each other at the closest, "
Out[1]: Array{(3,),Clipping(a_max=[2. 2. 2.], a_min=[0. 0. 0.], name=Cl([0. 0. 0.],[2. 2. 2.]), shape=(3,))}[recombination=average,sigma=1.0]:[1. 1. 1.]
```
This is now on master and will be included in next release.
Don't hesitate to reopen or open another issue if you have any problem!
