### ISSUE TITLE
Support for warm start

### ISSUE THREAD

**Issue by ytsaig** [facebookresearch/nevergrad#486]
First, thank you for your work on this package, I've really enjoyed working with it! I was wondering if there's support for (or future plans to support) warm starting an optimization algorithm. Specifically, for a sequential algorithm like CMA or TBPSA, I'd like to initially feed in a list of candidate parameter vectors and associated evaluations rather than starting the search from scratch. This can also be quite handy for meta-learning.

**Comment by jrapin** [comment]
Hi,
Most algorithms (including CMA and TBPSA) support telling candidates which have not been asked, so this can be used for warm starting it.
In the latest versions (there have been a few breaking changes lately, and will be a few others until v0.4.0) this can be done with:
```python
candidate = optimizer.instrumentation.spawn_child(new_value=XXX)
optimizer.tell(candidate, ZZZZ)
```
Is that what you wanted?

Also, on a related note, with the newer versions it's become easier to initialize with a prior:
`instrumentation = ng.p.Array(init=[12, 12]).set_mutation(sigma=4)` to initialize at `[12, 12]` with a standard deviation of 4.

**Comment by ytsaig** [comment]
Yes, that will do it, thanks! Follow up question: when you say most algorithms support it, what happens if I use tell() without ask() with an algorithm that doesn't support it - will an error be thrown, or will it silently ignore the values?

I haven't had a chance to play with the new API, but initializing variables looks very useful, I'll give it a try.

**Comment by jrapin** [comment]
I find it more useful to know explicitly what happens, so the optimizers will explicitly raise a specific exception, example here:
https://github.com/facebookresearch/nevergrad/blob/c908a4951d9e37ef3d8100c1f619dcab949660db/nevergrad/optimization/optimizerlib.py#L325-L326

**Comment by ytsaig** [comment]
Thanks for the quick reply, agreed, an explicit error is clearer.
