### ISSUE TITLE
Advice: running multiple independent optimizations in parallel?

### ISSUE THREAD

**Issue by claforte** [facebookresearch/nevergrad#50]
I'd like to run multiple instances of optimizers (e.g. 2 instances of TBPSA + several instances of CMA), each responsible for theoretically independent sets of variables. Are there any known limitations/assumptions in the NeverGrad code that would break if I tried it?

Background info: each evaluation I run takes 90s during which I could gather GBs' worth of measurements. Some of the sets of variables I'm trying to optimize affect non-overlapping measurements. e.g. they might affect different frames in a video. I would like to break down the complexity of the optimization problem using the approach above. Your advice would be very appreciated!

BTW if this already is supported by NeverGrad, I think it would be worth documenting it as I'm sure others will run into similarly complex optimization problems. I'll be happy to document it if you recommend where, e.g. in machinelearning.md?

**Comment by teytaud** [comment]
I fully agree that this should be documented! I am on it.
Yes, Nevergrad, with the ask-and-tell interface, is fully compatible with this kind of problem, and I should include such an example.

**Comment by claforte** [comment]
Merci M. Teytaud pour cette confirmation! I look forward to trying it out, once I can extract more detailed results from my experiments. :-)

**Comment by jrapin** [comment]
Closing this since this seems answered. There may be some work on this in the near future on our side though. Don't hesitate to reopen or ask new questions if need be ;)
