### ISSUE TITLE
Missing EU project reference in the merged PR

### ISSUE THREAD

**Issue by Corwinpro** [facebookresearch/nevergrad#529]
We have recently merged pull request #484 which was done as a part of the EU-funded project FORCE. It is my completely my fault that I forgot to mention this, and didn't include any reference to the grant in the source code.

I was wondering if it could be possible to add this short note to the `hypervolume.py` file?

```
This work is implemented under the Formulations and Computational Engineering (FORCE) project within Horizon 2020
(`NMBP-23-2016/721027 <https://www.the-force-project.eu>`_).
```

I would very much appreciate if you could give me a permission to add it.

Thank you!

**Comment by jrapin** [comment]
Sure, if it does not impact the licensing I can't see any problem with this.
Open a PR and we can merge it as long as the file keeps the initial header.
