### ISSUE TITLE
Add requirements.txt to nevergrad-0.1.1.tar.gz on PyPI

### ISSUE THREAD

**Issue by sunpoet** [facebookresearch/nevergrad#54]
## Steps to reproduce

  1. Download nevergrad-0.1.1.tar.gz from PyPI
  2. Extract and install it

## Observed Results

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 10, in <module>
    with open('requirements.txt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
*** Error code 1
```

## Solution

Add [requirements.txt](https://github.com/facebookresearch/nevergrad/blob/master/requirements.txt) to the tarball

**Comment by jrapin** [comment]
Sorry for the delay in closing this, I am waiting for some code that I would want to be included.

**Comment by jrapin** [comment]
Now on Pypi ;) Thanks again!
