### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by Darel13712** [facebookresearch/nevergrad#611]
## Steps to reproduce

  1. Open [getting_started.rst](https://github.com/facebookresearch/nevergrad/blob/master/docs/getting_started.rst)
  2. See notes section

## Observed Results
It says

> with `zhs` you will need to run `pip install 'nevergrad[all]'`

## Expected Results
I believe you wanted to say `zsh` instead of `zhs`

I don't want to open separate PR for this as I haven't found any other mistakes yet, but you might want to fix it.

**Comment by jrapin** [comment]
Hi,
Thanks for pointing out! I just fixed it ;)
In the future, don't hesitate to create a PR even for one typo, it's always helpful ;)
