### ISSUE TITLE
Uncommenting fails for custom file extensions

### ISSUE THREAD

**Issue by Dominik1123** [facebookresearch/nevergrad#62]
## Steps to reproduce

1. Create script with custom extensions (one that is not part of [the defaults](https://github.com/facebookresearch/nevergrad/blob/8d6381cbb750ce22e8f6ca3f288a2f37ebe4c1b8/nevergrad/instrumentation/folderfunction.py#L57)).
2. Place inside some line which should be interpolated, e.g. `// @nevergrad@ var = NG_G{0, 1};`.
3. Create a corresponding `FolderFunction`.
4. (By the way, it looks like the extension `.m` is missing the `.` [here](https://github.com/facebookresearch/nevergrad/blob/8d6381cbb750ce22e8f6ca3f288a2f37ebe4c1b8/nevergrad/instrumentation/folderfunction.py#L57).)

## Observed Results

The following exception is raised ([location in code](https://github.com/facebookresearch/nevergrad/blob/8d6381cbb750ce22e8f6ca3f288a2f37ebe4c1b8/nevergrad/instrumentation/instantiate.py#L41)):

```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    func = FolderFunction(folder, command, extensions=['.custom'])
  File ".../lib/python3.6/site-packages/nevergrad/instrumentation/folderfunction.py", line 61, in __init__
    self.instrumentized_folder = InstrumentizedFolder(folder, extensions=extensions, clean_copy=clean_copy)
  File ".../lib/python3.6/site-packages/nevergrad/instrumentation/instantiate.py", line 127, in __init__
    instru_f = InstrumentizedFile(fp)
  File ".../lib/python3.6/site-packages/nevergrad/instrumentation/instantiate.py", line 63, in __init__
    lines = [(l if LINETOKEN not in l else uncomment_line(l, ext)) for l in lines]
  File ".../lib/python3.6/site-packages/nevergrad/instrumentation/instantiate.py", line 63, in <listcomp>
    lines = [(l if LINETOKEN not in l else uncomment_line(l, ext)) for l in lines]
  File ".../lib/python3.6/site-packages/nevergrad/instrumentation/instantiate.py", line 42, in uncomment_line
    pattern += r'(?P<linetoken>' + comment_chars[extension] + r" *" + LINETOKEN + r" *)"
KeyError: '.custom'
```

## Expected Results

Since [`FolderFunction`](https://github.com/facebookresearch/nevergrad/blob/8d6381cbb750ce22e8f6ca3f288a2f37ebe4c1b8/nevergrad/instrumentation/folderfunction.py#L31) supports custom extensions, I'd expect this class to work with uncommenting the relevant lines in corresponding scripts. However since the comment chars are [hardcoded here](https://github.com/facebookresearch/nevergrad/blob/8d6381cbb750ce22e8f6ca3f288a2f37ebe4c1b8/nevergrad/instrumentation/instantiate.py#L38) it fails to do so.

Would be nice to have some extra module or list / dict that stores available file types, together with possible extensions and comment chars, so the user can extend this list as needed. Or alternatively pass a dict to `extensions` which contains the relevant information. For example:

```python
file_types = {'.c':  '//', '.py': '#', ...}
```

or

```python
FolderFunction(..., extensions={'.custom': '//'})
```

and then `InstrumentedFile` would take the same dict of custom extensions and comment chars.

Right now the defaults are anyway duplicated [here](https://github.com/facebookresearch/nevergrad/blob/8d6381cbb750ce22e8f6ca3f288a2f37ebe4c1b8/nevergrad/instrumentation/folderfunction.py#L57) and [here](https://github.com/facebookresearch/nevergrad/blob/8d6381cbb750ce22e8f6ca3f288a2f37ebe4c1b8/nevergrad/instrumentation/instantiate.py#L125).

## Relevant Code

```python
import os
from pathlib import Path
import tempfile
from nevergrad.instrumentation import FolderFunction

folder = Path(tempfile.gettempdir()).joinpath('test')
script = folder.joinpath('test.custom')
os.mkdir(folder)

with open(script, 'w') as fh:
    fh.write('// @nevergrad@ var = NG_G{0, 1};\nprint(var);')

command = ['custom_app', os.path.join(*script.parts[-2:])]
func = FolderFunction(folder, command, extensions=['.custom'])
```

**Comment by jrapin** [comment]
Hi, thanks for pointing out.
I probably won't have time this week to deal with this (you're welcome to propose a PR ;) ), but you're right that there should be a way to add custom extensions. I feel using a dict is a bit cumbersome though, how about adding a way to register a new extension into a global variable which holds the "comment pattern"? That would help avoiding duplication as well (and making the same mistake twice about "m" files indeed...)

**Comment by jrapin** [comment]
Btw, FYI, in the near future (couple of weeks or one month), I plan to make breaking changes on the way to instrument external code through `FolderFunction` #45. Instead of setting specific tokens like for each type of variable like `NG_G{0, 1}`, it will become something like NG_VAR{name, comment}, and the choice of the variable type will have to be done through the FolderFunction.
This way it will be simpler to update instrumentation. In any case, it will make it much easier to maintain and add new variable types.
I hope this will fit your needs.

**Comment by jrapin** [comment]
Closing since @Dominik1123 's PR #65 solved this (don't hesitate to open again if I have missed something)
Thanks again!

**Comment by jrapin** [comment]
Hi @Dominik1123 ,
PR #73 (now on master, but not in any release yet) changes a lot of the process of instantiating external files. It helps being much more flexible (now the choice of prior is done through Python, not in the external files) and makes the code simpler and more robust. I hope it will suit your needs as well, let me know if you have any problem.

**Comment by Dominik1123** [comment]
Hello @jrapin , thanks for the info, I checked it out and it looks good! It feels much more natural to have the relevant parts within the Python script and separated from the tokenized script.
