### ISSUE TITLE
Interfacing Nevergrad with more Bayesian optimization libraries ?

### ISSUE THREAD

**Issue by teytaud** [facebookresearch/nevergrad#622]
We have an interface with a single Bayesian optimization library.
We have no parallel version, or no version for the noisy case.
We might either
- explore a better use of the existing bayesian optimization library
- implement an interface towards another bayesian optimization library

The example of SPSA is one of the simplest examples of implementation of an algorithm, so this could be used as a model regarding how to include a new algorithm: https://github.com/facebookresearch/nevergrad/blob/2ef9cb8cc3e1b769745f05dc1c8689386459e88c/nevergrad/optimization/optimizerlib.py#L686

(_internal_ask should provide the next point to be tested, this is the key part of implementing an optimization algorithm)

**Comment by teytaud** [comment]
e.g. Turbo ?

**Comment by herilalaina** [comment]
Hi @teytaud. I am interested to add interface for two widely-used bayesian optimization library (for hyper-parameters tuning): [SMAC](https://github.com/automl/SMAC3) and [Hyperopt](https://github.com/hyperopt/hyperopt). 
It may also be interesting for #618. What do you think ?

**Comment by teytaud** [comment]
Each of those (SMAC, HyperOpt, and #618) is super useful, and to the best of my knowledge there is nobody on it!

**Comment by herilalaina** [comment]
Ok, I will take up this issue.
