### ISSUE TITLE
Optimizer always trying the same points 

### ISSUE THREAD

**Issue by franchesoni** [facebookresearch/nevergrad#716]
## Steps to reproduce

  1. Set up an optimizer with a parametrization
  2. Run optimizer.minimize()
  3. Print values being tested

## Observed Results

  * What happened?  This could be a description, log output, etc.
The argument of the objective function are always the same

## Expected Results

  * What did you expect to happen?
The optimizer tries new values
## Relevant Code

  ```
from concurrent import futures

import nevergrad as ng
import numpy as np


class myobj:
    def __init__(self):
        self.params = ng.p.Dict(
            kernel=ng.p.Log(lower=3, upper=2000).set_integer_casting()
        )

    def get_optimizer(self, parametrization, dictA):
        optimizer = ng.optimizers.NGO(
            parametrization=parametrization,
            budget=dictA["budget"],
            num_workers=dictA["workers"],
        )
        return optimizer

    def fn(self, params, dictA, X, Y):
        print(params)
        kvalue = params['kernel']
        print(kvalue)
        return kvalue * np.mean((Y - X)**2)

    def optimize_params(self, dictA, X, Y):
        # breakpoint()
        parametrization = ng.p.Instrumentation(
            self.params, dictA=dictA, X=X, Y=Y
        )
        optimizer = self.get_optimizer(parametrization, dictA)
        with futures.ThreadPoolExecutor(
            max_workers=optimizer.num_workers
        ) as executor:
            r = optimizer.minimize(
                self.fn, executor=executor, batch_mode=False
            )
        return r


obj = myobj()
dictA = {'budget':5, 'workers':2}
recom = obj.optimize_params(dictA, np.zeros(3), np.ones(3))
print('recommendation: ')
print(*recom.args)

  ```

I am sure I am doing something wrong, but I can not detect what. Any helpful hand is welcome.

**Comment by jrapin** [comment]
From what I could see, in this situation NGO chooses `DoubleFastGADiscreteOnePlusOne` which seemingly does not work in dimension 1 (cc @teytaud). I'll need to add a test for this.
For the time being you need either:
- add another variable
- use a different optimizer

**Comment by franchesoni** [comment]
Well, I am going for the second option: "use a different optimizer". However, which optimizers are suited for the parallel univariate optimization problem? I run all of them and got this:

## Working optimizers
[{'DE': ({'kernel': 39},)},
 {'TwoPointsDE': ({'kernel': 6},)},
 {'LhsDE': ({'kernel': 24},)},
 {'QrDE': ({'kernel': 8},)},
 {'NoisyDE': ({'kernel': 18},)},
 {'AlmostRotationInvariantDE': ({'kernel': 26},)},
 {'RotationInvariantDE': ({'kernel': 15},)},
 {'RecES': ({'kernel': 28},)},
 {'RecMixES': ({'kernel': 6},)},
 {'RecMutDE': ({'kernel': 4},)},
 {'ES': ({'kernel': 5},)},
 {'MixES': ({'kernel': 4},)},
 {'MutDE': ({'kernel': 8},)},
 {'RandomSearch': ({'kernel': 37},)},
 {'QORandomSearch': ({'kernel': 24},)},
 {'ORandomSearch': ({'kernel': 42},)},
 {'RandomSearchPlusMiddlePoint': ({'kernel': 32},)},
 {'MetaRecentering': ({'kernel': 6},)},
 {'MetaTuneRecentering': ({'kernel': 6},)},
 {'HAvgMetaRecentering': ({'kernel': 6},)},
 {'AvgMetaRecenteringNoHull': ({'kernel': 6},)},
 {'HaltonSearch': ({'kernel': 7},)},
 {'HaltonSearchPlusMiddlePoint': ({'kernel': 7},)},
 {'LargeHaltonSearch': ({'kernel': 7},)},
 {'ScrHaltonSearch': ({'kernel': 7},)},
 {'ScrHaltonSearchPlusMiddlePoint': ({'kernel': 7},)},
 {'HammersleySearch': ({'kernel': 6},)},
 {'HammersleySearchPlusMiddlePoint': ({'kernel': 7},)},
 {'ScrHammersleySearchPlusMiddlePoint': ({'kernel': 7},)},
 {'ScrHammersleySearch': ({'kernel': 6},)},
 {'QOScrHammersleySearch': ({'kernel': 9},)},
 {'OScrHammersleySearch': ({'kernel': 9},)},
 {'CauchyScrHammersleySearch': ({'kernel': 6},)},
 {'LHSSearch': ({'kernel': 11},)},
 {'CauchyLHSSearch': ({'kernel': 4},)},
 {'OnePlusOne': ({'kernel': 38},)},
 {'NoisyOnePlusOne': ({'kernel': 4},)},
 {'DiscreteOnePlusOne': ({'kernel': 18},)},
 {'CauchyOnePlusOne': ({'kernel': 3},)},
 {'OptimisticNoisyOnePlusOne': ({'kernel': 3},)},
 {'OptimisticDiscreteOnePlusOne': ({'kernel': 77},)},
 {'NoisyDiscreteOnePlusOne': ({'kernel': 77},)},
 {'EDA': ({'kernel': 50},)},
 {'PCEDA': ({'kernel': 13},)},
 {'MPCEDA': ({'kernel': 4},)},
 {'MEDA': ({'kernel': 4},)},
 {'TBPSA': ({'kernel': 42},)},
 {'NaiveTBPSA': ({'kernel': 97},)},
 {'NoisyBandit': ({'kernel': 32},)},
 {'PSO': ({'kernel': 8},)},
 {'RealSpacePSO': ({'kernel': 6},)},
 {'SplitOptimizer': ({'kernel': 44},)},
 {'Portfolio': ({'kernel': 6},)},
 {'CM': ({'kernel': 32},)},
 {'BO': ({'kernel': 3},)},
 {'cGA': ({'kernel': 105},)},
 {'NaiveIsoEMNA': ({'kernel': 27},)}]
## Optimizers that do not work
[{'NelderMead': '_ScipyMinimizeBase does not support parallelization'},
 {'Powell': '_ScipyMinimizeBase does not support parallelization'},
 {'RPowell': '_ScipyMinimizeBase does not support parallelization'},
 {'Cobyla': '_ScipyMinimizeBase does not support parallelization'},
 {'RCobyla': '_ScipyMinimizeBase does not support parallelization'},
 {'SQP': '_ScipyMinimizeBase does not support parallelization'},
 {'RSQP': '_ScipyMinimizeBase does not support parallelization'},
 {'DoubleFastGADiscreteOnePlusOne': 'Always the same point'},
 {'RecombiningPortfolioOptimisticNoisyDiscreteOnePlusOne': 'Always the same '
                                                           'point'},
 {'CMA': 'optimization in 1-D is not supported (code was never tested)'},
 {'DiagonalCMA': 'optimization in 1-D is not supported (code was never '
                 'tested)'},
 {'FCMA': 'Please install fcmaes (pip install fcmaes) to use FCMA optimizers'},
 {'SPSA': 'SPSA does not support parallelization'},
 {'ParaPortfolio': 'optimization in 1-D is not supported (code was never '
                   'tested)'},
 {'SQPCMA': 'optimization in 1-D is not supported (code was never tested)'},
 {'ASCMADEthird': 'optimization in 1-D is not supported (code was never '
                  'tested)'},
 {'ASCMADEQRthird': 'optimization in 1-D is not supported (code was never '
                    'tested)'},
 {'ASCMA2PDEthird': 'optimization in 1-D is not supported (code was never '
                    'tested)'},
 {'CMandAS2': 'optimization in 1-D is not supported (code was never tested)'},
 {'CMandAS3': 'optimization in 1-D is not supported (code was never tested)'},
 {'CMandAS': 'optimization in 1-D is not supported (code was never tested)'},
 {'MultiCMA': 'optimization in 1-D is not supported (code was never tested)'},
 {'TripleCMA': 'optimization in 1-D is not supported (code was never tested)'},
 {'MultiScaleCMA': 'optimization in 1-D is not supported (code was never '
                   'tested)'},
 {'chainCMAPowell': '_ScipyMinimizeBase does not support parallelization'},
 {'NGO': 'Always the same point'},
 {'Shiwa': 'Always the same point'}]
### Code

```python
from concurrent import futures
from pprint import pprint

import nevergrad as ng
import numpy as np


class myobj:
    def __init__(self, optim):
        self.params = ng.p.Dict(
            kernel=ng.p.Log(lower=3, upper=2000).set_integer_casting()
        )
        self.optim = optim
        self.params_list = []

    def get_optimizer(self, parametrization, dictA):
        optimizer = self.optim(
            parametrization=parametrization,
            budget=dictA["budget"],
            num_workers=dictA["workers"],
        )
        return optimizer

    def fn(self, params, dictA, X, Y):
        # print(params)
        kvalue = params['kernel']
        self.params_list.append(kvalue)
        return kvalue * np.mean((Y - X)**2)

    def optimize_params(self, dictA, X, Y):
        # breakpoint()
        parametrization = ng.p.Instrumentation(
            self.params, dictA=dictA, X=X, Y=Y
        )
        optimizer = self.get_optimizer(parametrization, dictA)
        with futures.ThreadPoolExecutor(
            max_workers=optimizer.num_workers
        ) as executor:
            r = optimizer.minimize(
                self.fn, executor=executor, batch_mode=False
            )
        assert len(set(self.params_list))>1, 'Always the same point'
        return r




dictA = {'budget':5, 'workers':2}
optimizers = list(ng.optimizers.registry.items())
successes, failures = [], []

for name, optim in optimizers:
    try:
        obj = myobj(optim)
        recom = obj.optimize_params(dictA, np.zeros(3), np.ones(3))
        successes.append({name: recom.args})
    except Exception as e:
        failures.append({name: str(e)})


print('## Working optimizers')
pprint(successes)
print('## Optimizers that do not work')
pprint(failures)
```

**Comment by jrapin** [comment]
Thanks for the info!
#712 will fix this
Not sure what is the best option for your case (@teytaud?)
If you have a budget of 5 and only 1 variable + parallelization 2 I doubt there is much of a difference between all optimizers. I would tend to use NGO (after the fix is merged), OnePlusOne or one of the one shot optimizers (HaltonSearch, LHSSearch etc)

**Comment by jrapin** [comment]
(this got close through the PR, please reopen or create a new issue for further questions)
