### ISSUE TITLE
Suggesting a point breaks when one of the parameters is a constant numpy array

### ISSUE THREAD

**Issue by alvarovalcarce** [facebookresearch/nevergrad#721]
## Steps to reproduce
```
import nevergrad as ng
import numpy as np


constant_param = np.zeros(3, dtype=int)
param = ng.p.Instrumentation(ng.p.Choice(["a", "b", "c"]), constant_param)
optim = ng.optimizers.OnePlusOne(parametrization=param, budget=100)
optim.suggest("c", constant_param)
```

## Observed Results

Traceback (most recent call last):
  in <module>
    optim.suggest("c", constant_param)
  File "C:\Program Files\Python37\lib\site-packages\nevergrad\optimization\base.py", line 219, in suggest
    self._suggestions.append(self.parametrization.spawn_child(new_value=new_value))
  File "C:\Program Files\Python37\lib\site-packages\nevergrad\parametrization\core.py", line 332, in spawn_child
    child.value = new_value
  File "C:\Program Files\Python37\lib\site-packages\nevergrad\parametrization\container.py", line 52, in value
    core.as_parameter(self[k]).value = val
  File "C:\Program Files\Python37\lib\site-packages\nevergrad\parametrization\container.py", line 52, in value
    core.as_parameter(self[k]).value = val
  File "C:\Program Files\Python37\lib\site-packages\nevergrad\parametrization\core.py", line 405, in value
    if not (value == self._value or value is self._value):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## Expected Results

I did not expect the insertion of a constant numpy array (i.e., constant_param) to throw an exception.

## Relevant Code
I believe the problem lies in line 405 of file *nevergrad\parametrization\core.py*, which currently looks like this:
  ```
  if not (value == self._value or value is self._value):
  ```

The equality only works for basic types, but throws an exception if value is a numpy ndarray.

**Comment by jrapin** [comment]
Hi,
Thanks for the bug report. I thought this had already beenn solved but I was obviously wrong :s I'll try a fix asap (a bit busy these days, if you want to give it a try, you're welcome to it ;) I think you pinned down the correct line)

**Comment by jrapin** [comment]
This should now be solved on master, please reopen if it is still failing for you, and open another issue if you find more unsupported types.
Thanks again!

**Comment by alvarovalcarce** [comment]
This works now. Thanks for the fast response!
