### ISSUE TITLE
Duplicate Functions In Corefuncs.py?

### ISSUE THREAD

**Issue by Capybasilisk** [facebookresearch/nevergrad#724]
I was looking at corefuncs.py and noticed that two benchmark functions (deceptivepath and deceptivemultimodal) have, as far as I can see, the exact same code. 

Is that intended?

**deceptivepath():**
  ```
@registry.register
def deceptivepath(x: np.ndarray) -> float:
    """A function which needs following a long path. Most algorithms fail on this.
    The path becomes thiner as we get closer to the optimum."""
    assert len(x) >= 2
    distance = np.sqrt(x[0] ** 2 + x[1] ** 2)
    if distance == 0.0:
        return 0.0
    angle = np.arctan(x[0] / x[1]) if x[1] != 0.0 else np.pi / 2.0
    invdistance = (1.0 / distance) if distance > 0.0 else 0.0
    if np.abs(np.cos(invdistance) - angle) > 0.1:
        return 1.0
    return float(distance)
  ```
**deceptivemultimodal():**
```
@registry.register
def deceptivemultimodal(x: np.ndarray) -> float:
    """Infinitely many local optima, as we get closer to the optimum."""
    assert len(x) >= 2
    distance = np.sqrt(x[0] ** 2 + x[1] ** 2)
    if distance == 0.0:
        return 0.0
    angle = np.arctan(x[0] / x[1]) if x[1] != 0.0 else np.pi / 2.0
    invdistance = int(1.0 / distance) if distance > 0.0 else 0.0
    if np.abs(np.cos(invdistance) - angle) > 0.1:
        return 1.0
    return float(distance)
```
Maybe **deceptiveillcond()** as well? But that one looks a little different.

As I cannot find much information on these functions, please help me with the following questions:

Are these functions scalable? Can dimensions be set to x = 1000?

Are they solvable in finite time by an average modern computer with a SHADE-type algorithm?

**Comment by teytaud** [comment]
They are not the same: invdistance is different.
The rationale is that the "int" adds plenty of local optima.

We have figures somewhere, let me try to find plots.

Yes, the functions work in arbitrarily high dimension; however they probably become very hard quickly...

**Comment by teytaud** [comment]
deceptivepath: a very thin path to the optimum.
deceptiveillcond: a condition number that goes to infinity near the optimum
deceptivemultimodal: more and more local minima as we get closer to the optimum

These functions are designed for being super hard.

**Comment by Capybasilisk** [comment]
Ah, ok, thank you. I should have read the code more carefully.
I'll close the thread now.
