### ISSUE TITLE
Pyomo ?

### ISSUE THREAD

**Issue by teytaud** [facebookresearch/nevergrad#738]
Pyomo has quite a lot of models.
My guess is that Nevergrad could be competitive on the kind of models they are considering.
We might implemented a function which takes as input a Pyomo model, and then
- builds a Nevergrad instrumentation corresponding to this Pyomo model
- builds a ExperimentFunction corresponding to this Pyomo model

**Comment by pacowong** [comment]
Hi, I am Paco.

I would like to help. I may have figured out how to set the evaluation function and made a pull request. However, I would like to know if the goal is to support all model components in Pyomo [1]. 

[1] https://pyomo.readthedocs.io/en/stable/pyomo_modeling_components/index.html

**Comment by teytaud** [comment]
Hello! Imho even a minimal support of simple cases would be great! Possibly with an error if something does not fit.
If it works on at least one of the examples on the pyomo page it's very cool :-)

**Comment by teytaud** [comment]
Mostlly solved! We might still add stuff, e.g. concrete models in experiments.py.

**Comment by teytaud** [comment]
Congrats @pacowong for solving this :-)
