### ISSUE TITLE
PicklingError: Can't pickle nevergrad.optimization.utils.Archive

### ISSUE THREAD

**Issue by veronicaCode** [facebookresearch/nevergrad#744]
In my case, I used `optimizer.ask()` and `optimizer.tell()` independently.
Optimizer can't be dumped into pickle when `num_tell` exceed 1000.

``` python
# sample
import nevergrad as ng

def test(a, b, c):
    return a + b + c

params = {
    "a": ng.p.Scalar(lower=0, upper=1, init=0).set_mutation(sigma=0.2),
    "b": ng.p.TransitionChoice([1, 2, 3]),
    "c": ng.p.TransitionChoice([x for x in range(200)])
}
optimizer = ng.optimizers.registry["TBPSA"](parametrization=ng.p.Instrumentation(**params))
args = [optimizer.ask() for x in range(1000)]
for arg in args:
    optimizer.tell(arg, test(**arg.kwargs))

optimizer.dump("./test_dump_optimizer.pkl")
```
I got the error below
``` python
PicklingError: Can't pickle nevergrad.optimization.utils.Archive[nevergrad.optimization.utils.MultiValue]: it's not the same object as nevergrad.optimization.utils.Archive
```
It seems that `pruning` will change `optimizer.archive` type and make object different.

**Comment by jrapin** [comment]
Hi, thanks for pointing out.
I think I know exactly where this is coming from, but I can't reproduce, which python version are you using?

**Comment by jrapin** [comment]
Reproduced in the CI which is running python 3.6.

**Comment by jrapin** [comment]
@veronicaCode this should be solved in master, please reopen if this does not work for you ;)

**Comment by veronicaCode** [comment]
@jrapin Thank u very much!! It's work now :D
