### ISSUE TITLE
Bayesian Optimization Ask Tell fails with Choice

### ISSUE THREAD

**Issue by atlasd** [facebookresearch/nevergrad#756]
## Steps to reproduce

I'm running into an error when I try to use a `Choice` variable with Bayesian Optimization using the ask-tell interface. It claims the value is not registered when I call tell, but I used the suggest-ask-tell pattern, so it should be there.

## Observed Results

Getting an error on the tell call that claims 
```
ValueError: Call does not match registered
```
This appears to be caused by rounding errors when the arrays are tested for equality.

## Expected Results

I would expect that this would run fine.

## Relevant Code

```
import nevergrad as ng


instrumentation = ng.p.Instrumentation(
    x1=ng.p.Scalar(lower=0, upper=1000), 
    x2=ng.p.Scalar(lower=0, upper=1000), 
    x3=ng.p.Choice(list(range(100)))
)

def func(x1, x2, x3):
    return (lambda x1, x2, x3: x1 ** 2 + 1/(x2 + 2) + x1 * x2 + x3)(x1, x2, x3)

starting_ask = 100
optim = ng.optimizers.ParametrizedBO(initialization='Hammersley')(
    parametrization=instrumentation, 
    budget=starting_ask * 2, 
    num_workers=1
)



starting_params = [optim.ask().value for  _ in range(starting_ask)]
starting_tell = [func(*args, **kwargs)  for args, kwargs in starting_params]

preexplained_guesses = [optim.ask() for _ in range(starting_ask)]

for ask, tell in zip(starting_params, starting_tell):
    optim.suggest(*ask[0], **ask[1])
    ask_ = optim.ask()
    optim.tell(candidate=ask_, value=tell)

postexplained_guesses = [optim.ask() for _ in range(starting_ask)]

```

**Comment by jrapin** [comment]
Hey,
Sorry for the delay, I am currently a bit busy and probably will be until next week :s 
I'll try to come back to you asap

**Comment by atlasd** [comment]
Sounds good - thanks!

**Comment by jrapin** [comment]
Hey, this should now be fixed on master.
Please close if this works for you as well

On a side note is there any reason you use `suggest` here?
If you kept track of the `Parameter` instances in `starting_params` you could use them for the `tell` without requiring to create suggestions:
```python
starting_params = [optim.ask()for  _ in range(starting_ask)]
starting_tell = [func(*p.args, **p.kwargs)  for p in starting_params]
```

**Comment by atlasd** [comment]
Yeah motivated by me not tracking the original parameterization, but I suspect you're correct and I could just do a better job of that.

Thanks for taking care of this!
