### ISSUE TITLE
Scalar lower bound > 0 leads to ValueError

### ISSUE THREAD

**Issue by fmder** [facebookresearch/nevergrad#764]
## Steps to reproduce

```python
ng.p.Scalar(lower=0.1).sample()
```

## Observed Results

```python
----> 1 param = ng.p.Scalar(lower=0.1)

~/venvs/ml/lib/python3.7/site-packages/nevergrad/parametrization/data.py in __init__(self, init, lower, upper, mutable_sigma)
    466             self.set_mutation(sigma=(upper - lower) / 6)  # type: ignore
    467         if any(a is not None for a in (lower, upper)):
--> 468             self.set_bounds(lower=lower, upper=upper, full_range_sampling=bounded and no_init)
    469 
    470     @property  # type: ignore

~/venvs/ml/lib/python3.7/site-packages/nevergrad/parametrization/data.py in set_bounds(self, lower, upper, method, full_range_sampling, a_min, a_max)
    256         checker = BoundChecker(*bounds)
    257         if not checker(self.value):
--> 258             raise ValueError("Current value is not within bounds, please update it first")
    259         if not (lower is None or upper is None):
    260             if (bounds[0] >= bounds[1]).any():  # type: ignore

ValueError: Current value is not within bounds, please update it first
```

## Expected Results

I would have expected a sample between 0.1 and infinity.

**Comment by jrapin** [comment]
> I would have expected a sample between 0.1 and infinity.

The question here is "which" then ;)
All parameters hold an initial value, the current behavior of scalar is probably not intuitive enough: init is set to (lower + upper) / 2 if both bounds are provided, 0 otherwise. But since you want it to be above 0.1, neither option works, hence the error.
What would be a better behavior (or error message) in you opinion?

**Comment by fmder** [comment]
If a single bound is provided, maybe it could be used. But at the same time I understand the current behaviour. I think it is only counter when defining a parameter space otherwise it makes total sense to "require" an initial value.

**Comment by jrapin** [comment]
> If a single bound is provided, maybe it could be used

Depending on the type of constraint, sampling on the bound can have weird/silent border effects (or even be completely unwanted). I would rather avoid making this call automatically so I prefer raising an error. Is there anyway we could make the error message clearer?

**Comment by jrapin** [comment]
I'll close this as I haven't come up with better option, feel free to reopen if you have any idea.
