### ISSUE TITLE
Range Span in Standardized Space

### ISSUE THREAD

**Issue by pacowong** [facebookresearch/nevergrad#792]
## Steps to Reproduce
OS: Windows 10
Numpy version 1.18.1
Nevergrad version: 0.4.2
Code is shown below.

## Relevant Code and Observed Results
I tried to understand the meaning of standardized space and the method `set_standardized_data`.
The programs were written to record the "choice transition", which helps me to understand range spanned by each choice, but I cannot understand the results. Could someone explain?

### Program 1
```python
import nevergrad as ng
import numpy as np

all_choices = [f"C{j}" for j in range(0, 10)]
params = ng.p.TransitionChoice(all_choices)
last_value = None
for i in np.linspace(-2.0, 2.0, num=1000):
    cur_value = params.set_standardized_data([i]).spawn_child().value
    if last_value:
        if last_value != cur_value:
            print(f"{last_value} -> {cur_value} @{i}")
            last_value = cur_value
    else:
        last_value = cur_value
```

It produces the following results:
```
C0 -> C1 @0.19419419419419404
C1 -> C2 @0.2022022022022023
C2 -> C3 @0.21021021021021014
C3 -> C4 @0.21421421421421405
C4 -> C5 @0.2182182182182184
C5 -> C6 @0.22222222222222232
C6 -> C7 @0.23023023023023015
C7 -> C8 @0.23423423423423406
C8 -> C9 @0.24224224224224233
```

### Program 2
```python
all_choices = [f"C{j}" for j in range(0, 10)]
params = ng.p.TransitionChoice(all_choices)
last_value = None
for i in np.linspace(-1.0, 2.0, num=1000):
    cur_value = params.set_standardized_data([i]).spawn_child().value
    if last_value:
        if last_value != cur_value:
            print(f"{last_value} -> {cur_value} @{i}")
            last_value = cur_value
    else:
        last_value = cur_value
```

It produces the following results:
```
C1 -> C0 @-0.996996996996997
C0 -> C1 @0.16816816816816815
C1 -> C2 @0.17717717717717707
C2 -> C3 @0.18018018018018012
C3 -> C4 @0.1861861861861862
C4 -> C5 @0.18918918918918926
C5 -> C6 @0.19519519519519513
C6 -> C7 @0.19819819819819817
C7 -> C8 @0.20120120120120122
C8 -> C9 @0.21021021021021014
```

The results are the same even I set different seed numbers by `params.random_state.seed(10)`

## Expected Results
I expect the results of the two programs are similar.

**Comment by jrapin** [comment]
A few information first, I'll dig further into it asap:
- Transition choice is expected to be deterministic
- the value is mapped (deterministically) into an index
- it is supposed to be uniformly distributed over the choice if we sample with a Gaussian (in other wards, we map to the index using `scipy.stats.norm.cdf`)

Then again from your output, it looks buggy so I need to have a closer look :s

**Comment by jrapin** [comment]
Got it.
`set_standardized_data` needs a reference. It's actually an optional argument because in many cases, the reference is the initial value, so since you do `set_standardized_data` on your parameter (and not on it's child) you actually keep shifting the value instead of using a fixed reference.
You should do: `params.spawn_child().set_standardized_data([i]).value`
indeed, this way you keep `params` as your reference, and then set the value.
Is that clearer?

**Comment by pacowong** [comment]
Thanks. I got what you mean. To test my understanding, I tried to change the initial value, which is originally 0. Looks good!

### Program 3
```python
all_choices = [f"C{j}" for j in range(0, 10)]
params = ng.p.TransitionChoice(all_choices)
params.set_standardized_data([1])
last_value = None
for i in np.linspace(-2.5, 2.5, num=1000):
    cur_value = params.spawn_child().set_standardized_data([i]).value
    if last_value:
        if last_value != cur_value:
            print(f"{last_value} -> {cur_value} @{i}")
            last_value = cur_value
    else:
        last_value = cur_value
```
It produces the following results:
```
C0 -> C1 @-1.2787787787787788
C1 -> C2 @-0.8383383383383383
C2 -> C3 @-0.5230230230230231
C3 -> C4 @-0.25275275275275266
C4 -> C5 @0.0025025025025025016
C5 -> C6 @0.25775775775775767
C6 -> C7 @0.5280280280280278
C7 -> C8 @0.8433433433433435
C8 -> C9 @1.2837837837837838
```

### Program 4
```python
all_choices = [f"C{j}" for j in range(0, 10)]
params = ng.p.TransitionChoice(all_choices)
params.set_standardized_data([1]) #Note the difference
last_value = None
for i in np.linspace(-2.5, 2.5, num=1000):
    cur_value = params.spawn_child().set_standardized_data([i]).value
    if last_value:
        if last_value != cur_value:
            print(f"{last_value} -> {cur_value} @{i}")
            last_value = cur_value
    else:
        last_value = cur_value
```
It produces the following results:
```
C0 -> C1 @-2.27977977977978
C1 -> C2 @-1.8393393393393394
C2 -> C3 @-1.524024024024024
C3 -> C4 @-1.2487487487487487
C4 -> C5 @-0.9984984984984986
C5 -> C6 @-0.7432432432432432
C6 -> C7 @-0.4729729729729728
C7 -> C8 @-0.1576576576576576
C8 -> C9 @0.2827827827827827
```
