### ISSUE TITLE
Some special kind of Conditions in Instrumentation 

### ISSUE THREAD

**Issue by lucasplagwitz** [facebookresearch/nevergrad#793]
## Question

Hey,
I've linked an example with my problem (does not raise any error, only a problem in content).  Let's say I want to optimize via these SVC Params.
Not all of them work together. The coef0 is ignored when kernel=="rbf".
Is there a way to build some Conditions in your Instrumentations for such a problem?
On my first look of your build in conditions, they return an infty, but nevergrad tries to optimize them together, right? 
Please let me know if you implemented anything for that or could imagine for future versions.

## Relevant Code

  ```
 from sklearn.datasets import load_breast_cancer
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
import nevergrad as ng

X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

def svc_training(**kwargs) -> float:
    print(str(kwargs))
    instance = SVC(**kwargs)
    instance.fit(X_train, y_train)
    return f1_score(y_test, instance.predict(X_test))

parametrization = ng.p.Instrumentation(
    C=ng.p.Scalar(lower=1, upper=2).set_integer_casting(),
    kernel=ng.p.Choice(["rbf", "poly"]),
    coef0=ng.p.Scalar(lower=0, upper=10)
)

optimizer = ng.optimizers.NGO(parametrization=parametrization, budget=100)
recommendation = optimizer.minimize(svc_training)

# show the recommended keyword arguments of the function
print(recommendation.kwargs)
print(svc_training(**recommendation.kwargs))
  ```

**Comment by jrapin** [comment]
> Is there a way to build some Conditions in your Instrumentations for such a problem?

The following would work:
```python
ng.p.Choice([
    ng.p.Dict(kernel="rbf", C=ng.p.Scalar(lower=1, upper=2).set_integer_casting()),
    ng.p.Dict(kernel="poly", C=ng.p.Scalar(lower=1, upper=2).set_integer_casting(), coef0=ng.p.Scalar(lower=0, upper=10))
])
```
However:
- that would duplicate the `C` parameter (which is probably a good idea since the optimal value may be different for different methods)
- you would need to change your function to take a dict as input instead of keyword args (basically that means removing the `**`)
- most optimizers will not differentiate which parameters are "active" in a candidate or not. I have no idea if that is important or not :s

> On my first look of your build in conditions, they return an infty

What do you mean by this, I can't recall any case where that should return infinity

**Comment by lucasplagwitz** [comment]
Really nice, that's what I was looking for. 
Please ignore the infinity comment - I was just thinking about your cheap constraints.
Thank's for your quick instruction.

> most optimizers will not differentiate which parameters are "active" in a candidate or not. I have no idea if that is important or not :s

I'd be surprised if it made no difference. In hyperparmeter optimization the cost per objective can become very high. So I do not want to test the "same" setting multiple times. I agree that it depends on the implementation, but normally I would say smaller search space => more efficient optimization.

**Comment by jrapin** [comment]
Oh I had started answering on this but then got caught by something else and forgot sorry

> I'd be surprised if it made no difference. In hyperparameter optimization the cost per objective can become very high. So I do not want to test the "same" setting multiple times.

I'd be surprised too, and then again I am often surprised :D.
The thing is that currently most optimizers in nevergrad use a vectorial representation of the parameters, which does not differentiate between "active" and "ignored" parameters. This allows to have very generic and simple to implement powerful methods. But it's losing some information indeed, and currently the methods that would handle it are a bit less sophisticated.
