### ISSUE TITLE
How to make a simple optimization with constraints that does not exceed max attempt?  

### ISSUE THREAD

**Issue by LofoSo** [facebookresearch/nevergrad#799]
## Steps to reproduce
def square(x):
    return sum((x - .5)**2)

optimizer = ng.optimizers.OnePlusOne(parametrization=10, budget=100)
# define a constraint on first variable of x:
optimizer.parametrization.register_cheap_constraint(lambda x: x[0] > 0)
optimizer.parametrization.register_cheap_constraint(lambda x: x[0] <= 1)
optimizer.parametrization.register_cheap_constraint(lambda x: x[1] > 0)
optimizer.parametrization.register_cheap_constraint(lambda x: x[1] <= 1)
optimizer.parametrization.register_cheap_constraint(lambda x: x[2] > 0)
optimizer.parametrization.register_cheap_constraint(lambda x: x[2] <= 1)
optimizer.parametrization.register_cheap_constraint(lambda x: x[3] > 0)
optimizer.parametrization.register_cheap_constraint(lambda x: x[3] <= 1)
optimizer.parametrization.register_cheap_constraint(lambda x: x[4] > 0)
optimizer.parametrization.register_cheap_constraint(lambda x: x[4] <= 1)
optimizer.parametrization.register_cheap_constraint(lambda x: x[5] > 0)
optimizer.parametrization.register_cheap_constraint(lambda x: x[5] <= 1)
optimizer.parametrization.register_cheap_constraint(lambda x: x[6] > 0)
optimizer.parametrization.register_cheap_constraint(lambda x: x[6] <= 1)
optimizer.parametrization.register_cheap_constraint(lambda x: x[7] > 0)
optimizer.parametrization.register_cheap_constraint(lambda x: x[7] <= 1)
recommendation = optimizer.minimize(square)
print(recommendation.value)

## Observed Results

  warnings.warn(f"Could not bypass the constraint after {MAX_TENTATIVES} tentatives, sending candidate anyway.")
and the constraints are not respected anymore (?)

## Expected Results

 an array [0.5]*8

**Comment by teytaud** [comment]
Thanks for sharing your experience!
Actually you should be using an instrumentation for specifying the bounds, rather than adding constraints.

Something like 
parametrization=ng.Array(shape=(8,))
parametrization.set_bounds(lower=0., upper=1.)
optimizer = ng.optimizers.OnePlusOne(parametrization=parametrization, budget=100)

details here: https://facebookresearch.github.io/nevergrad/parametrization_ref.html

**Comment by LofoSo** [comment]
thank you so much
