### ISSUE TITLE
Hello-world install question

### ISSUE THREAD

**Issue by salamanders** [facebookresearch/nevergrad#8]
## Steps to reproduce

Install nevergrad

```
pip3 install -e git+git@github.com:facebookresearch/nevergrad@master#egg=nevergrad
Obtaining nevergrad from git+git@github.com:facebookresearch/nevergrad@master#egg=nevergrad
  Cloning git@github.com:facebookresearch/nevergrad (to revision master) to ./src/nevergrad
Warning: Permanently added the RSA host key for IP address '192.30.255.112' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Command "git clone -q git@github.com:facebookresearch/nevergrad /Users/ME/Documents/workspace/temp/src/nevergrad" failed with error code 128 in None
```

ok.  trying git clone and `python3 setup.py install` method.  That seems to work.

run the sample program:

python3 mynevergrad.py

```
from nevergrad.optimization import optimizerlib

def square(x):
    return (x - .5)**2

optimizer = optimizerlib.OnePlusOne(dimension=1, budget=100, num_workers=5)
recommendation = optimizer.optimize(square, executor=None, batch_mode=True)
```

## Observed Results

```
Traceback (most recent call last):
  File "mynevergrad.py", line 6, in <module>
    from nevergrad.optimization import optimizerlib
ModuleNotFoundError: No module named 'nevergrad.optimization'
```

## Expected Results

It should run the sample

## Relevant Code

```
import pkg_resources
for d in pkg_resources.working_set:
	print(d)
```
DOES include `nevergrad 0.1.0`

This is very likely an install, python3, homebrew "installed in user directory", or paths issue, but given that `nevergrad 0.1.0` shows up in the list, it is odd...

**Comment by teytaud** [comment]
Maybe just a problem of PYTHONPATH ?
not sure, but maybe

========
pushd src/nevergrad      
(or navigate to a place in which there is something at "ls nevergrad/optimization/optimizer_lib")
export PYTHONPATH=`pwd`:$PYTHONPATH
popd 
========

Does it solve it ?

**Comment by jrapin** [comment]
Hi,
Thank you for your feedback, I have updated the pip install instruction to use http instead of ssh, which should work now. I will also update the dummy package in Pypi as soon as I can (but not a lot of time to do this in this period of year ;) ) which will make installation simpler (`pip install nevergrad`).

Concerning your second issue, it does strongly look like a path issue. Are you sure you are using the same install in both cases ?
I would advice trying in a virtualenv:
```
python3 -m venv testvenv
source testvenv/bin/activate
which pip  # should be in the venv
which python  # should be as well, and in the virtualenv python=python3
pip install git+https://github.com/facebookresearch/nevergrad@master#egg=nevergrad
python mynevergrad.py
```

**Comment by jrapin** [comment]
@salamanders can you confirm it works better now?

**Comment by eyaler** [comment]
i had the exact same two issues. i can confirm that both are solved for me.

**Comment by jrapin** [comment]
Thanks, I'll close this issue then, please open a new one if there is any problem ;)

**Comment by salamanders** [comment]
`git+https://github.com/facebookresearch/nevergrad@master#egg=nevergrad` worked, but had the same `No module named 'nevergrad.optimization'` error.

The 'virtualenv' comment solved it for me, thank you!
