### ISSUE TITLE
Passing parameters and additional variable to register_cheap_constraint

### ISSUE THREAD

**Issue by agodavarthy** [facebookresearch/nevergrad#810]
I have an optimiazation problem with a linear constraint. My parameter is an list of variable, which I declare as a python list of ng.p.Scalar. I declared it this way:

## Method 1)

                inp_arr = []
                for i in range(len(weights)):
                    inp = ng.p.Scalar()
                    inp.set_integer_casting()
                    inp.set_bounds(lower_bounds[i], upper_bounds[i])    
                    inp_arr.append(inp)
Then I delcare my constraint as follows:

                optimizer = ng.optimizers.DE(parametrization=inp_arr, budget=1000)
                optimizer.parametrization.register_cheap_constraint(lambda inp_arr: (a * b == bias) for a, b in zip(inp_arr, vals))

my constraint is p1 * v1 + p2 * v2 + .....pn* vn = bias. 

### Observed Results

But when I run it I encounter the following error:
    optimizer = ng.optimizers.DE(parametrization=inp_arr, budget=1000)
  File "/home/agodavarthy/.local/lib/python3.6/site-packages/nevergrad/optimization/base.py", line 575, in __call__
    run = self._OptimizerClass(parametrization=parametrization, budget=budget, num_workers=num_workers, **config)  # type: ignore
  File "/home/agodavarthy/.local/lib/python3.6/site-packages/nevergrad/optimization/differentialevolution.py", line 80, in __init__
    super().__init__(parametrization, budget=budget, num_workers=num_workers)
  File "/home/agodavarthy/.local/lib/python3.6/site-packages/nevergrad/optimization/base.py", line 98, in __init__
    self.parametrization.freeze()  # avoids issues!
AttributeError: 'list' object has no attribute 'freeze'

## Method 2)

I tried Implementing the params as ng.p.Array as follows: 

                inp_arr = ng.p.Array(shape=(1, len(weights)))
                inp_arr.set_integer_casting()
                inp_arr.set_bounds(lower_bounds, upper_bounds)

And they use the same function for constraint: I get this problem:

    optimizer.parametrization.register_cheap_constraint(lambda inp_arr: (a * b == bias) for a, b in zip(inp_arr, vals))
   TypeError: zip argument #1 must support iteration

Essentailly I need to use the parameters I am passing to the objective function along with some additional variable to define my constraint. Please advice.

**Comment by jrapin** [comment]
Hi
Sorry for the delay in answering.
you can't use a list as Parameter (I'll make the error more explicit).
You should use:
```python
optimizer = ng.optimizers.DE(parametrization=ng.p.Tuple(*inp_arr), budget=1000)
```

**Comment by jrapin** [comment]
as to this:
```python
optimizer.parametrization.register_cheap_constraint(lambda inp_arr: (a * b == bias) for a, b in zip(inp_arr, vals))
```
a few remarks:
- if you use an Array as parameter, you'd be better off using an np.ndarray syntax: `lambda inp_arr: (inp_arr * vals== bias).all()`
- the current implementation of this tries to sample values until one of them satisfies the constraint. I'm afraid with equality constraints this does not happen often enough so the constraint may end up being ignored. @teytaud is currently adding a new option for constraints using a penalization instead, that may work better for you, but it's not ready yet

**Comment by agodavarthy** [comment]
Thanks for the reply.

**Comment by jrapin** [comment]
I'll close this since it seems answered, but please feel welcome to reopen (or open a new issue) if you have more questions
