### ISSUE TITLE
CMA TypeError : "NoneType" ... when "Max tentative" exceeded

### ISSUE THREAD

**Issue by TokyAxel** [facebookresearch/nevergrad#845]
### 
The program seeks to optimize the function under certains constraints. When we arrives on a CMA optimizer case, and that "Max TENTATIVE" is exceeded, the program bug. The fact is CMA sometimes works and sometimes doesn't.
We got this error : 

### Observed Results : *TypeError: '>' not supported between instances of 'float' and 'NoneType'*

*Full traceback*
/home/misa/.local/lib/python3.6/site-packages/nevergrad/parametrization/data.py:281: UserWarning: Bounds are 0.833333333 sigma away from each other at the closest, you should aim for at least 3 for better quality.
  warnings.warn(f"Bounds are {min_dist} sigma away from each other at the closest, "
/home/misa/.local/lib/python3.6/site-packages/nevergrad/parametrization/core.py:279: UserWarning: Lambda as constraint is not advised because it may not be picklable.
  warnings.warn("Lambda as constraint is not advised because it may not be picklable.")
(3_w,7)-aCMA-ES (mu_w=2.3,w_1=58%) in dimension 3 (seed=<module 'time' (built-in)>, Wed Oct  7 15:33:48 2020)
/home/misa/.local/lib/python3.6/site-packages/nevergrad/optimization/base.py:330: UserWarning: Could not bypass the constraint after 1000 tentatives, sending candidate anyway.
  warnings.warn(f"Could not bypass the constraint after {MAX_TENTATIVES} tentatives, sending candidate anyway.")
/home/misa/.local/lib/python3.6/site-packages/cma/utilities/utils.py:347: UserWarning: function values with index []/[4] are nan/None and will be set to the median value 6623.330932194596 (class=CMAEvolutionStrategy method=ask iteration=1)
  ')')
Traceback (most recent call last):
  File "main_test.py", line 40, in <module>
    data=mix.simuleMix(current_usage_coef=[0.6, 0.2, 0.7, 0.95], optimize_with = ["CMA"], budgets = [50],step = 2, time_index = 24)
  File "/home/misa/opt_project/MixSimulator/MixSimulator.py", line 195, in simuleMix
    time_interval = time_interval, optimize_with = optimize_with, budgets = budgets, step = step, time_index = t)
  File "/home/misa/opt_project/MixSimulator/MixSimulator.py", line 129, in optimizeMix
    demand=new_demand, lost=0, optimize_with = optimize_with, budgets = budgets, instrum = instrum, step=step)        
  File "/home/misa/opt_project/MixSimulator/SegmentOptimizer.py", line 143, in getOptimumUsageCoef
    prod_cost_optimal = self.__optimizer.opt_With(self.prod_cost_objective_function, constrains, optimize_with,budgets, step= step)
  File "/home/misa/opt_project/MixSimulator/nevergradBased/Optimizer.py", line 266, in opt_With
    optimizer.tell(x, loss)
  File "/home/misa/.local/lib/python3.6/site-packages/nevergrad/optimization/base.py", line 256, in tell
    self._internal_tell_candidate(candidate, value)
  File "/home/misa/.local/lib/python3.6/site-packages/nevergrad/optimization/optimizerlib.py", line 1545, in _internal_tell_candidate
    opt.tell(candidate, value)
  File "/home/misa/.local/lib/python3.6/site-packages/nevergrad/optimization/base.py", line 256, in tell
    self._internal_tell_candidate(candidate, value)
  File "/home/misa/.local/lib/python3.6/site-packages/nevergrad/optimization/optimizerlib.py", line 323, in _internal_tell_candidate
    self._parents = sorted(self._to_be_told, key=lambda c: c.loss)[: self._num_spawners]
TypeError: '>' not supported between instances of 'float' and 'NoneType'

### Expected Results

 In the case of the other optimizers (like OnePlusOne), it still suggests a candidate and the algorithm does not stop.

### Relevant Code : 
Maybe the problem is in the constraints. This was the way we initiate it.

  ```python
#optimization under constraints
        chaining_algo = ng.optimizers.Chaining(self.__optimizers,current_budgets[:-1])
        optimizer = chaining_algo(parametrization=self.get_parametrization(), budget=self.get_budget())
        if constraints != None:
            #if contraint initiate
            try: 
                optimizer.parametrization.register_cheap_constraint(lambda x: constraints["carbonProd"](x) <= constraints["carbonProdLimit"])
                #Environmental constraint
                
            except: #if no contraint assigned
                pass
            try:
                tolerance = 2 * 10**(math.log10(constraints["demand"] + constraints["lost"])-2)
                min_prod = constraints["demand"] + constraints["lost"]
                optimizer.parametrization.register_cheap_constraint(lambda x: np.abs(constraints["production"](x) - min_prod) < tolerance )
                #Demand constraint
            except:
                pass
            try:
                optimizer.parametrization.register_cheap_constraint(lambda x: (np.array(x) <= constraints["availability"]).all())
                #Availability constraint
            except:
                pass
            try:
                fully_used = np.array([1]*len(constraints["availability"])).astype("float64")
                not_used = np.array([0]*len(constraints["availability"])).astype("float64")
                for index in constraints["nonTuneable"]:
                    fully_used[index] = 0.1
                    not_used[index] = 0.1
                optimizer.parametrization.register_cheap_constraint(lambda x: ((np.abs(np.array(x) - constraints["availability"]) <= fully_used) + (x <= not_used)).all())
            except:
                pass
        
        #let's minimize
        recommendation = optimizer.minimize(func_to_optimize, verbosity=0)
  ```

**Comment by jrapin** [comment]
Hi,
Thanks for the report. The bug should already have disappeared (on master, I'll release a minor version soon with the fix) because of an unrelated diff yesterday #854. However I am afraid it is just hiding a deeper problem because it should not have happened in the first place, I'll take a closer look asap

**Comment by jrapin** [comment]
What does your function if it receives an invalid set of parameters? Does it return None? That would explain it (and should not bug anymore indeed)

**Comment by TokyAxel** [comment]
Hi :-) Thanks for the reply and update.
Our function calculates the least cost of the power plant mix, it takes as parameters the value of type float and must always return a float, but we will check on our side if it is return a nan value or else, on some differents params.

**Comment by TokyAxel** [comment]
We've just updated nevergrad but still get the following error when the max tentative is exceeded. It differs a bit from the above errors : 

```
/home/misa/.local/lib/python3.6/site-packages/nevergrad/parametrization/data.py:281: UserWarning: Bounds are 1.0 sigma away from each other at the closest, you should aim for at least 3 for better quality.
  warnings.warn(f"Bounds are {min_dist} sigma away from each other at the closest, "
/home/misa/.local/lib/python3.6/site-packages/nevergrad/parametrization/core.py:296: UserWarning: Lambda as constraint is not advised because it may not be picklable.
  warnings.warn("Lambda as constraint is not advised because it may not be picklable.")
(8_w,17)-aCMA-ES (mu_w=5.1,w_1=31%) in dimension 96 (seed=<module 'time' (built-in)>, Thu Oct 15 12:38:53 2020)
/home/misa/.local/lib/python3.6/site-packages/nevergrad/optimization/base.py:424: UserWarning: Could not bypass the constraint after 1000 tentatives, sending candidate anyway.
  warnings.warn(f"Could not bypass the constraint after {MAX_TENTATIVES} tentatives, sending candidate anyway.")
NOTE (module=cma, class=CMAEvolutionStrategy, method=tell, iteration=0):  function values=[None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
Traceback (most recent call last):

  File "<ipython-input-6-5e57d93e3d1d>", line 1, in <module>
    runfile('/home/misa/opt_project/retest.py', wdir='/home/misa/opt_project')

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/misa/opt_project/retest.py", line 20, in <module>
    eva.evaluate(mix,10,1000,optimizer_list = ["CMA"], indicator_list = ["loss", "elapsed_time"],carbonProdLimit = 9999999999999999999999, penalisation = 1000, num_worker= 1)

  File "/home/misa/opt_project/MixSimulator/Evaluation.py", line 225, in evaluate
    time_interval = time_interval, optimizer = opt_index, step = sequence, penalisation = penalisation, time_index = time_index)

  File "/home/misa/opt_project/MixSimulator/MixSimulator.py", line 192, in optimizeMix
    step = step, k = self.get_penalisation_cost())

  File "/home/misa/opt_project/MixSimulator/nevergradBased/Optimizer.py", line 172, in optimize
    x = optimizer.ask()

  File "/home/misa/.local/lib/python3.6/site-packages/nevergrad/optimization/base.py", line 416, in ask
    candidate = self._internal_ask_candidate()

  File "/home/misa/.local/lib/python3.6/site-packages/nevergrad/optimization/optimizerlib.py", line 1565, in _internal_ask_candidate
    return opt.ask()

  File "/home/misa/.local/lib/python3.6/site-packages/nevergrad/optimization/base.py", line 421, in ask
    self._internal_tell_candidate(candidate, float("Inf"))

  File "/home/misa/.local/lib/python3.6/site-packages/nevergrad/optimization/optimizerlib.py", line 320, in _internal_tell_candidate
    self.es.tell(*args)

  File "/home/misa/.local/lib/python3.6/site-packages/cma/evolution_strategy.py", line 2568, in tell
    if np.isscalar(function_values[0][0]):

TypeError: 'NoneType' object is not subscriptable
```

**Comment by teytaud** [comment]
Hopefully better now --- but there is still room for improvement regarding constraints.

**Comment by TokyAxel** [comment]
Thank you for reply :+1:
