### ISSUE TITLE
Save, Interrupt and Resume

### ISSUE THREAD

**Issue by fsmosca** [facebookresearch/nevergrad#848]
#### Question

Is it possible to save, stop and resume your optimization. Something like run an optimization, save data for budgets that were done, there is power interruption. Later resume the optimization but load the saved data and the optimizer will continue from there.

Thanks for this great lib.

**Comment by jrapin** [comment]
Hi,
This should be possible using [`Optimizer.dump` and `Optimizer.load`](https://facebookresearch.github.io/nevergrad/optimizers_ref.html#nevergrad.optimizers.base.Optimizer.dump), it's basically only a shortcut `pickle.load` and `dump` which can be handy. If I need to interrupt, a Ctrl+C is expected to be safe.
Would that solve your issue?

**Comment by fsmosca** [comment]
Thanks, I will try that.
