### ISSUE TITLE
ParametrizedBO with initialization=None raises StopIteration exception

### ISSUE THREAD

**Issue by fsmosca** [facebookresearch/nevergrad#861]
## Steps to reproduce

  1. Use ParametrizedBO as optimizer with initialization=None (the default), see relevant code.

## Observed Results

```
Traceback (most recent call last):
  File ".\lib\site-packages\nevergrad\optimization\optimizerlib.py", line 1457, in _internal_ask_candidate
    x_probe = next(self.bo._queue)
  File ".\lib\site-packages\bayes_opt\bayesian_optimization.py", line 25, in __next__
    raise StopIteration("Queue is empty, no more objects to retrieve.")
StopIteration: Queue is empty, no more objects to retrieve.
```

## Expected Results

  Perhaps it should not raise a StopIteration exception because the initialization default value is None in the first place.

If initialization is either of ["random", "Hammersley", "LHS"] then there is no issue.

I discovered this issue in my [game parameter optimizer](https://github.com/fsmosca/Lakas) using nevergrad.

Perhaps don't use [None](https://github.com/facebookresearch/nevergrad/blob/d2bca44b1d50e30c5d96d3342a4cab505b82e429/nevergrad/optimization/optimizerlib.py#L1516) as default value.

## Relevant Code

  ```python
 import nevergrad as ng


def lossf(**x):
    a = x['a']
    return -a ** 2 + 1


arg = {'a': ng.p.Scalar(init=4, lower=1, upper=10).set_integer_casting()}
instrum = ng.p.Instrumentation(**arg)

gp_param = {'alpha': 1e-3, 'normalize_y': True,
            'n_restarts_optimizer': 5, 'random_state': None}

# initialization can be ["random", "Hammersley", "LHS"], default=None
my_opt = ng.optimizers.ParametrizedBO(gp_parameters=gp_param, initialization=None)
optimizer = my_opt(parametrization=instrum, budget=10)

recommendation = optimizer.minimize(lossf)
print(recommendation.value)
  ```

## Nevergrad
version: 0.4.2.post1

**Comment by jrapin** [comment]
BO indeed needs some kind of initialization, I reverted to the default package initialization if not provided.

While I am at it, is there any reason you use a ng.p.Instrumentation? You could simplify your code this way:
```python
def lossf(a):
    return -a ** 2 + 1

instrum = ng.p.Scalar(init=4, lower=1, upper=10).set_integer_casting()
```

**Comment by fsmosca** [comment]
Will test it later.

Thanks for the hint. Regarding my sample code, it was from a user input from command line that I am processing something like this.
```
... --input-param "{'RazorMargin': {'init':527, 'lower':100, 'upper':700}, 'FutMargin': {'init':227, 'lower':50, 'upper':400}, 'KingAttackWeights[2]': {'init':81, 'lower':0, 'upper':200}, 'eMobilityBonus[0][7]': {'init':20, 'lower':-100, 'upper':100}, 'mMobilityBonus[1][7]': {'init':63, 'lower':-100, 'upper':150}, 'eMobilityBonus[3][21]': {'init':168, 'lower':-100, 'upper':300}, 'eThreatByRook[1]': {'init':46, 'lower':0, 'upper':200}, 'mThreatByMinor[3]': {'init':77, 'lower':0, 'upper':200}, 'eThreatByKing': {'init':89, 'lower':0, 'upper':200}, 'eThreatByPawnPush': {'init':39, 'lower':0, 'upper':200}}" ...
```
Then convert that input param using [this](https://github.com/fsmosca/Lakas/blob/39664e7513bfd0c20fd10b2968a7d3898eb47d9d/lakas.py#L472).

**Comment by fsmosca** [comment]
PR is ok, no more issue encountered from my test.
