### ISSUE TITLE
TypeError: cannot pickle 'module' object with CMA

### ISSUE THREAD

**Issue by fsmosca** [facebookresearch/nevergrad#884]
## Steps to reproduce

  1. Run the relevant code

## Observed Results

```
0.4.2.post2
Traceback (most recent call last):
  File "../AppData/Roaming/JetBrains/PyCharmCE2020.2/scratches/scratch2.py", line 27, in <module>
    optimizer.dump(data_fn)
  File "..\venv\lib\site-packages\nevergrad\optimization\base.py", line 211, in dump
    pickle.dump(self, f)
TypeError: cannot pickle 'module' object
```

## Relevant Code

```python
import nevergrad as ng


def lossf(**x):
  a = x['a']
  b = x['b']
  return -a ** 2 + 1 + b


print(ng.__version__)


data_fn = 'opt_cma.dat'

arg = {'a': ng.p.Scalar(init=4, lower=1, upper=10).set_integer_casting(),
       'b': ng.p.Scalar(init=4, lower=2, upper=12).set_integer_casting()}

param = ng.p.Instrumentation(**arg)

optimizer = ng.optimizers.CMA(parametrization=param, budget=20)

for _ in range(optimizer.budget):
    x = optimizer.ask()
    loss = lossf(**x.kwargs)
    optimizer.tell(x, loss)

    optimizer.dump(data_fn)

print(f'best param: {optimizer.provide_recommendation().value[1]}')
```

**Comment by jrapin** [comment]
Hi,
Thanks for pointing out.
pycma was referencing time module for initilization of the random number generator, even if it was of no use. I overrode it and added a test to make sure all optimizers can be dumped

**Comment by jrapin** [comment]
(and the test happens to fail on optimizers relying on threads to use scipy, which is logical... I'll figure out how to deal with this later I think)

**Comment by fsmosca** [comment]
> Hi,
> Thanks for pointing out.
> pycma was referencing time module for initilization of the random number generator, even if it was of no use. I overrode it and added a test to make sure all optimizers can be dumped

@jrapin 
Could you release an update perhaps 0.4.2.post3. Thanks.

**Comment by jrapin** [comment]
Hi,
Done! Turns out it's `0.4.2.post5` though because of some issues I did not expect during the deployment :s
