### ISSUE TITLE
Basic Example in Documentation Fails to Converge

### ISSUE THREAD

**Issue by knoam** [facebookresearch/nevergrad#901]
## Steps to reproduce

The basic example provided on the main GitHub page is not converging properly. I get a highly variable result, such as:
{'learning_rate': 0.03949360675530159, 'batch_size': 3, 'architecture': 'conv'}
{'learning_rate': 0.03162277660168379, 'batch_size': 6, 'architecture': 'conv'}
{'learning_rate': 0.15893513466214484, 'batch_size': 4, 'architecture': 'conv'}
{'learning_rate': 0.06675075457685112, 'batch_size': 6, 'architecture': 'conv'}

Increasing budget doesn't help much. However, changing to 
```optimizer = ng.optimizers.OnePlusOne(parametrization=parametrization, budget=100)```
as in the official documentation results in better convergence. I am just getting started, so maybe this is expected behavior. But in that case, perhaps it makes sense to change GitHub's example to use the same OnePlusOne optimizer.

Here's the example code from the GitHub main page (note that it uses `NGOpt`):

  ```
import nevergrad as ng

def fake_training(learning_rate: float, batch_size: int, architecture: str) -> float:
    # optimal for learning_rate=0.2, batch_size=4, architecture="conv"
    return (learning_rate - 0.2)**2 + (batch_size - 4)**2 + (0 if architecture == "conv" else 10)

# Instrumentation class is used for functions with multiple inputs
# (positional and/or keywords)
parametrization = ng.p.Instrumentation(
    # a log-distributed scalar between 0.001 and 1.0
    learning_rate=ng.p.Log(lower=0.001, upper=1.0),
    # an integer from 1 to 12
    batch_size=ng.p.Scalar(lower=1, upper=12).set_integer_casting(),
    # either "conv" or "fc"
    architecture=ng.p.Choice(["conv", "fc"])
)

optimizer = ng.optimizers.NGOpt(parametrization=parametrization, budget=100)
recommendation = optimizer.minimize(fake_training)

# show the recommended keyword arguments of the function
print(recommendation.kwargs)
  ```

I am using version '0.4.2.post2' with Python 3.8.6

**Comment by jrapin** [comment]
This example is explicitly a bit difficult in its formulation because it is definitely not continuous.
However I would expect it to work better indeed. @teytaud any reason NGOpt does not perform as well as OnePlusOne on this?

**Comment by teytaud** [comment]
Very interesting. I am on it.

**Comment by teytaud** [comment]
Ok there is a very easy fix actually. 
NGOpt still redirects to NGOpt4.
The new version, NGOpt8, is merged and works corrrectly in that case.
But NGOpt still redirects to NGOpt4.
I send a fix now.

Thansk a lot @knoam , this helps a lot.

**Comment by teytaud** [comment]
First PR merged, results should be ok now, further PR coming for further improvement & adding tests.

**Comment by teytaud** [comment]
A big thank you, @knoam , this was a serious issue and the fact that tests do not catch it is also interesting..
