### ISSUE TITLE
How to break the iterations of optimization once the objective function reaches the certain value?

### ISSUE THREAD

**Issue by machanic** [facebookresearch/nevergrad#912]
The optimizier has a budget argument indicates the iteration number of the algorithm. How to break (terminate) the iterations of optimization once the objective function reaches the certain value? 

If nevergrad can terminate the algorithm early, this would save much time.

Thank you.

**Comment by jrapin** [comment]
Hi,
For now this is unfortunately not directly possible through the `minimize` method, there is this issue to track the feature: #714 but this is not yet on our roadmap.
That being said, it's not very difficult to hack a solution using the [callback system](https://facebookresearch.github.io/nevergrad/optimizers_ref.html#callbacks). You could register a callback that raises an exception when you reach the value you want, and catch this exception externally.
Would that work for you?

**Comment by machanic** [comment]
@jrapin Thank you very much! However, I still confused and I am not very familar with the callback system. I am now reading the document webpage that you give me to understand how to do. **Can you give me a simple example code to show how to do this??** Thank you very very much!

**Comment by jrapin** [comment]
Hi,
I've added a simple callback for doing this.
The documentation is here: https://facebookresearch.github.io/nevergrad/optimizers_ref.html#nevergrad.callbacks.EarlyStopping
