### ISSUE TITLE
Which paper refers to the algorithm of ng.optimizers.NGOpt?

### ISSUE THREAD

**Issue by machanic** [facebookresearch/nevergrad#916]
I am currently using `ng.optimizers.NGOpt` to optimize. However, I want to know the details of this optimizer. Which paper or code should I read to know the details?
Does this optimizer the evolutionary algorithm?

**Comment by teytaud** [comment]
Hello! 
Yes it uses evolutionary computation, but not only. 
There is a competence map, which automatically decides, given the types of variables, which algorithm should be used.
So many algorithms can be used:
- Differential Evolution,
- Evolution strategies,
- Powell,
- Cobyla,
- Various surrogate models.
(and I probably forget a few :-) ).

The original paper about this was https://arxiv.org/pdf/2004.14014.pdf (describing Shiwa).
NGOpt is a pointer to the current best method we have, and there have been several contributions making it better and better.

Happy to discuss more :-)

**Comment by machanic** [comment]
Can you tell me what is the algorithm used for discrete variable optimization?
I use the following code:
```
variables = ng.p.TransitionChoice([-1,1],repetitions=3072)
self.optimizer = ng.optimizers.NGOpt(parametrization=variables, budget=args.iterations)
```
And what is the algorithm used for continuous variable optimization?
```
init = self.from_unit_cube(np.random.rand(self.image.size(0), self.dims).ravel(), self.lb, self.ub).astype(np.float)
self.param = ng.p.Array(init=init).set_bounds(self.lb.ravel(), self.ub.ravel(), method='clipping')
self.optimizer = ng.optimizers.NGOpt(parametrization=self.param, budget=args.iterations)
```

**Comment by jrapin** [comment]
It's a bit hidding but you can print it:
```python
optimizer. _select_optimizer_cls()
```
