### ISSUE TITLE
Minimum Score Not Recorded

### ISSUE THREAD

**Issue by pacowong** [facebookresearch/nevergrad#947]
## Steps to reproduce
This is an issue discovered in my pull request (https://github.com/facebookresearch/nevergrad/pull/902). To isolate the issue, I have created a smaller test case.

```python
import nevergrad as ng
min_score = None

def fake_training(score: int) -> float:
    global min_score
    if min_score is None or min_score > score:
        min_score = score
    return score

def test(choice_size=1000, budget=300):
    global min_score
    min_score = None
    parametrization = ng.p.Instrumentation(score=ng.p.Choice(list(range(0, choice_size))))
    optimizer = ng.optimizers.OnePlusOne(parametrization=parametrization, budget=budget, num_workers=1)
    recommendation = optimizer.minimize(fake_training)
    print((min_score, recommendation.kwargs['score']))
    return min_score==recommendation.kwargs['score']
```

To run the test:
```python
for i in range(0, 100):
    if not test(1000, 300):
         break
```

## Observed Results
```python
(0, 0)
(1, 1)
(0, 0)
(2, 2)
(10, 10)
(9, 21)
```

## Expected Results
Print 100 tuples and the elements in each tuple should be the same.

## Investigation
The `_update_archive_and_bests` function in `nevergrad/optimization/base.py` should be responsible for incorrect behaviour.
I have checked that the minimum loss has been passed into this function but the archiving process may have some problems:
1. the value of `mvalue` can be `None` in `if mvalue is self.current_bests[name]`
2. Assertion file if `assert mvalue.parameter.loss == candidate.loss` is added before `if mvalue.parameter.loss > candidate.loss`
Not sure why this is the case because `fake_training` function is a deterministic function.

**Comment by jrapin** [comment]
Hi @pacowong 
Thanks for pointing this out. This was indeed an expected behavior which aim was to deal with noisy data. In this case however it was confusing and definitely suboptimal so we have updated the optimizers code. It should be way better indeed.

**Comment by pacowong** [comment]
Thanks.
